const assert=require('node:assert/strict');
const D=require('../src/data.js');
const Game=require('../src/engine.js');
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
function run(cls='kid',seed='test'){const g=new Game();g.newRun('Test',cls,seed);return g;}
function reachable(m,start){let queue=[start],seen=new Set([start.y*m.w+start.x]);for(let n=0;n<queue.length;n++){let p=queue[n];for(let [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){let x=p.x+dx,y=p.y+dy,k=y*m.w+x;if(x<0||y<0||x>=m.w||y>=m.h||seen.has(k)||m.tiles[k]==='#')continue;seen.add(k);queue.push({x,y});}}return seen;}
test('All eight districts have reachable objectives, exits and services across 100 seeds',()=>{for(let s=0;s<100;s++){let g=run('kid','city-'+s);for(let z=0;z<8;z++){g.travel(z);const m=g.map,r=reachable(m,m.start);assert.equal(m.entities.filter(e=>e.type==='gate').length,D.zones[z].links.length);for(const e of m.entities)assert.ok(r.has(e.y*m.w+e.x),`${s}/${z}: unreachable ${e.type} ${e.x},${e.y}`);assert.ok(m.entities.some(e=>e.type==='objective'));assert.ok(m.entities.some(e=>e.boss));assert.ok(m.entities.some(e=>e.type==='npc'));}}});
test('Same seed generates identical starting city',()=>assert.equal(run('kid','repeat').serialize(),run('kid','repeat').serialize()));
test('Saved game preserves RNG, inventory, map changes, quests and return visits',()=>{let g=run();let cache=g.map.entities.find(e=>e.type==='cache');g.loot(cache);g.travel(1);g.s.flags.objective1=true;let save=g.serialize(),restored=Game.load(save);assert.equal(restored.serialize(),save);assert.equal(g.rand(),restored.rand());restored.travel(0);assert.equal(restored.map.entities.find(e=>e.uid===cache.uid).opened,true);});
test('Solid walls stop line of sight, closed doors open in one turn',()=>{let g=run();let p=g.p;g.map.tiles[p.y*g.map.w+p.x+1]='#';assert.equal(g.los(p,{x:p.x+2,y:p.y}),false);g.map.tiles[p.y*g.map.w+p.x+1]='+';const x=p.x;g.move(1,0);assert.equal(p.x,x);assert.equal(g.tile(x+1,p.y),'.');assert.equal(g.s.turn,1);});
test('Every class ability functions and consumes a turn',()=>{for(const c of D.classes){let g=run(c.id);g.p.hp-=30;g.ability();assert.equal(g.s.turn,1,c.id);assert.ok(g.p.cooldown>0);assert.ok(g.p.energy<=g.p.maxEnergy);if(c.id==='medic')assert.ok(g.p.hp>g.p.maxHp-30);if(c.id==='engineer')assert.ok(g.map.entities.some(e=>e.type==='sentry'));}});
test('Specialization locks alternate path; tier prerequisites enforced',()=>{for(const c of D.classes){let g=run(c.id);g.p.level=5;g.p.points=6;const ts=D.talents.filter(t=>t.cls===c.id);assert.equal(g.learn(ts[2].id),false);assert.ok(g.learn(ts[0].id));assert.equal(g.learn(ts[3].id),false);assert.ok(g.learn(ts[1].id));assert.ok(g.learn(ts[2].id));assert.equal(g.learn(ts[2].id),false);}});
test('Crafting spends exact ingredients and yields working items',()=>{let g=run('engineer');for(const r of D.recipes){for(const [id,n]of Object.entries(r.cost))g.add(id,n+10);const before=g.count(r.id);assert.ok(Object.entries(g.recipeCost(r)).every(([id,n])=>g.count(id)>=n));g.craft(r.id);assert.equal(g.count(r.id),before+r.n);}});
test('Ranged combat requires ammo, damages target and wears equipment',()=>{let g=run('soldier'),p=g.p;g.map.entities=g.map.entities.filter(e=>e.type!=='enemy');g.map.tiles[p.y*g.map.w+p.x+2]='.';let e={uid:999,type:'enemy',name:'Target',x:p.x+2,y:p.y,hp:100,maxHp:100,damage:0,armor:0,range:1,ai:'guard',xp:10,status:{},alert:0};g.map.entities.push(e);g.vision();let ammo=g.count('ammo');g.attack(e);assert.ok(e.hp<100);assert.equal(g.count('ammo'),ammo-1);assert.ok(g.equipped('weapon').durability<100);g.take('ammo',g.count('ammo'));let hp=e.hp,t=g.s.turn;g.attack(e);assert.equal(e.hp,hp);assert.equal(g.s.turn,t);});
test('All objectives can resolve through force and change faction relations',()=>{for(let z=0;z<8;z++){let g=run('soldier');g.travel(z);g.map.entities=g.map.entities.filter(e=>e.type!=='enemy');let e=g.map.entities.find(e=>e.type==='objective');g.p.x=e.x;g.p.y=e.y;g.interact(e);g.choose('objective-force');assert.ok(g.prompt.options.some(x=>x.id==='objective-local'));g.choose('objective-local');assert.ok(g.s.flags['objective'+z]);assert.equal(g.s.quests['main'+z].state,'done');assert.ok(g.s.rep[D.zones[z].faction]>=20);assert.equal(g.p.fragments,1);}});
test('All escape requirements gate their actual ending',()=>{for(const route of ['train','air','echo']){let g=run('hacker');assert.equal(g.escapeReady(route),false);Object.assign(g.s.flags,{objective2:true,objective3:true,objective5:true,objective7:true});g.add('scrap',10);g.s.rep.crown=20;g.p.credits=200;g.p.fragments=3;g.s.time=20*60;assert.ok(g.escapeReady(route));g.escapePrompt(route);assert.equal(g.prompt.options[0].disabled,false);g.choose('end-'+route);assert.equal(g.s.ending.type,route);}});
test('All local contracts award once and consume required supplies',()=>{for(let z=0;z<8;z++){let g=run();g.travel(z);g.localJob();g.add('water',3);g.add('bandage',4);g.add('scrap',10);g.add('medkit',2);g.add('data',3);g.add('circuit',3);g.s.kills+=5;g.p.fragments=5;assert.ok(g.localReady(z));let credits=g.p.credits;g.completeLocal();assert.equal(g.p.credits,credits+60);g.completeLocal();assert.equal(g.p.credits,credits+60);}});
test('Trade stock persists, selling unequips, Chrome and Flesh install and remove',()=>{let g=run();g.p.credits=1000;let stock=g.shopStock(),n=stock.food;g.buy('food');assert.equal(stock.food,n-1);let uid=g.p.weapon;g.sell(uid);assert.equal(g.p.weapon,null);for(const id of ['eyes','blood','heart']){g.add(id);assert.ok(g.install(id));assert.ok(g.has(id));}g.removeAugment('eyes');assert.equal(g.has('eyes'),false);assert.equal(g.count('eyes'),1);});
test('Second heart prevents one death; next fatal injury ends the run',()=>{let g=run();g.p.augments.push('heart');g.damage(999,'test');assert.equal(g.s.ending,null);assert.equal(g.p.hp,35);g.damage(999,'test');assert.equal(g.s.ending.type,'death');const turn=g.s.turn;g.move(1,0);assert.equal(g.s.turn,turn);});
test('Sleeping advances days, consumes supplies and recovers fatigue',()=>{let g=run();g.p.x=g.map.start.x;g.p.y=g.map.start.y;g.p.fatigue=80;const before=g.p.food;g.choose('rest8');assert.ok(g.day>=2);assert.ok(g.p.food<before);assert.equal(g.p.fatigue,0);});
test('Entity ids and item references stay valid across the whole city',()=>{let g=run();for(let z=0;z<8;z++)g.travel(z);const ids=new Set();for(const m of Object.values(g.s.maps))for(const e of m.entities){assert.ok(!ids.has(e.uid));ids.add(e.uid);if(e.pool)for(const id of e.pool)assert.ok(D.items[id]);}for(const r of D.recipes){assert.ok(D.items[r.id]);for(const id of Object.keys(r.cost))assert.ok(D.items[id]);}});
console.log(`\n${passed} integration tests passed.`);
