/* Fractured City: Night Run — original game content. No external assets. */
(function(root){
'use strict';
const classes = [
 {id:'kid',name:'Street Kid',tag:'The city raised you. It never promised to keep you.',desc:'Find extra salvage, slip through service ducts, and make friends before enemies. Low armor; unmatched routes.',stats:[3,6,3,5,3,5],weapon:'knife',armor:'hoodie',ability:'Slipstream',effect:'Vanish for 5 turns and recover 12 energy. Adjacent enemies lose your trail.',paths:['Ghost','Fixer']},
 {id:'soldier',name:'Deserter',tag:'You remember which side of a rifle is safe.',desc:'Begin with a rifle and ammunition. Overwatch punishes advancing enemies. Loud, hungry, hard to stop.',stats:[5,3,6,5,2,2],weapon:'rifle',armor:'vest',ability:'Overwatch',effect:'For 5 turns, fire a free shot at the first visible enemy in range each turn. Uses ammunition.',paths:['Bastion','Deadeye']},
 {id:'hacker',name:'Wirewalker',tag:'Every locked door is a conversation.',desc:'Disable machines, open sealed caches and rewrite hostile security. Fragile in a straight fight.',stats:[2,4,3,4,7,4],weapon:'stunner',armor:'coat',ability:'Blackout',effect:'Stun all visible machines for 6 turns; living enemies for 2. Reveal the surrounding network.',paths:['Puppeteer','Architect']},
 {id:'medic',name:'Patch Doctor',tag:'There is still someone worth saving.',desc:'Heal without supplies, resist infection, and use medicine to resolve desperate encounters.',stats:[3,3,5,4,5,5],weapon:'scalpel',armor:'scrubs',ability:'Triage',effect:'Restore 26 health and clear bleeding, poison and burns. Costs 16 energy.',paths:['Lifeline','Plaguehand']},
 {id:'engineer',name:'Scrapper',tag:'Nothing is broken beyond its next purpose.',desc:'Salvage components, craft at lower cost and deploy a sentry that fights beside you.',stats:[4,3,5,3,6,3],weapon:'wrench',armor:'workcoat',ability:'Sentry',effect:'Deploy a 10-turn sentry. It attacks a visible hostile within 6 tiles every turn.',paths:['Machinist','Demolitionist']},
 {id:'sensitive',name:'Signal Touched',tag:'The radio said your name before you were born.',desc:'Sense the Echo, walk through thin walls, and burn enemies with impossible signals. Power invites attention.',stats:[2,5,3,6,5,3],weapon:'rod',armor:'shroud',ability:'Resonance',effect:'Deal 15 armor-piercing damage to visible enemies within 5 tiles. Gain 4 Echo exposure.',paths:['Witness','Hollow']}
];
// Attributes: strength, agility, endurance, perception, intellect, presence.
const items={};
function item(id,name,type,weight,value,props={}){items[id]={id,name,type,weight,value,...props};}
[
 ['knife','Notched switchblade',4,1,18,1,{bleed:0.3}],['pipe','Lead pipe',7,3,20,1,{}],['scalpel','Surgical scalpel',4,0.5,25,1,{bleed:0.5}],['wrench','Heavy wrench',7,2,28,1,{}],['rod','Tuning rod',5,1,35,2,{pierce:2}],['stunner','Arc prod',6,1.5,48,1,{stun:0.3}],['machete','Salvage machete',10,2,60,1,{bleed:0.3}],['hammer','Breach hammer',16,5,100,1,{pierce:3}],['katana','Monofilament saber',14,2,145,1,{pierce:5}],['claws','Carbon talons',12,0.5,125,1,{bleed:0.6}],
 ['pistol','Service pistol',8,2,70,6,{ammo:1,noise:8}],['rifle','Functioning rifle',12,4,140,9,{ammo:1,noise:12}],['shotgun','Short-barrel shotgun',18,4,115,4,{ammo:2,noise:14,spread:true}],['smg','Suppressed SMG',10,3,160,6,{ammo:2,noise:4}],['railgun','Industrial railcaster',24,7,250,11,{ammo:3,noise:16,pierce:6}],['crossbow','Cable crossbow',11,3,85,7,{ammo:1,noise:2}],['flamer','Foundry torch',14,5,135,3,{ammo:2,noise:8,burn:true}]
].forEach(([id,n,d,w,v,r,p])=>item(id,n,'weapon',w,v,{damage:d,range:r,durability:100,...p}));
[
 ['hoodie','Crew hoodie',1,1,15,{stealth:1}],['coat','Insulated coat',1,2,25,{resist:1}],['vest','Ballistic vest',3,4,70,{}],['scrubs','Clinic whites',1,1,20,{heal:1}],['workcoat','Riveted workcoat',2,3,45,{}],['shroud','Signal shroud',1,1,40,{echo:1}],['plate','Riot carapace',5,7,150,{agility:-1}],['mesh','Ghostweave suit',3,2,180,{stealth:2}],['hazmat','Sealed hazard suit',2,3,110,{resist:3}],['organic','Living mantle',4,2,160,{regen:1}]
].forEach(([id,n,a,w,v,p])=>item(id,n,'armor',w,v,{armor:a,...p}));
item('pack','Courier backpack','gear',1,45,{capacity:12});item('rig','Load-bearing frame','gear',3,100,{capacity:24});item('scope','Optical sight','mod',0.4,55,{desc:'Attach to the equipped weapon: +2 range.'});item('silencer','Sound baffle','mod',0.5,65,{desc:'Attach to the equipped weapon: reduce noise by 6.'});item('edge','Honed receiver','mod',0.5,60,{desc:'Attach to the equipped weapon: +3 damage.'});
item('ammo','Universal cartridges','ammo',0.05,3);item('scrap','Mechanical scrap','material',0.3,5);item('circuit','Intact circuit','material',0.2,15);item('cloth','Sterile cloth','material',0.1,4);item('chemical','Reagent vial','material',0.2,12);item('data','Encrypted data','valuable',0.1,35);item('jewelry','Old-world keepsake','valuable',0.2,45);
item('food','Sealed ration','consumable',0.5,15,{desc:'Restore 38 nutrition.'});item('water','Clean water','consumable',0.5,12,{desc:'Restore 42 hydration.'});item('medkit','Trauma kit','consumable',0.5,38,{desc:'Heal 32 HP and treat all injuries.'});item('bandage','Pressure dressing','consumable',0.1,12,{desc:'Heal 10 HP, stop bleeding.'});item('antidote','Broad-spectrum serum','consumable',0.2,24,{desc:'Cure poison and infection.'});item('stim','Reflex stimulant','consumable',0.1,30,{desc:'Restore 30 energy and suppress fatigue by 20; raises hunger.'});item('grenade','Fragmentation charge','consumable',0.5,40,{desc:'Throw at a visible target: 26 blast damage in a 2-tile radius.'});item('smoke','Smoke canister','consumable',0.3,22,{desc:'Become hidden for 7 turns.'});item('battery','High-density cell','consumable',0.4,25,{desc:'Restore 40 energy.'});item('repair','Field repair kit','consumable',0.5,28,{desc:'Restore equipped weapon durability.'});
[
 ['eyes','Spectral optics','chrome',2,'Vision +3; reveal hidden caches.'],['dermal','Subdermal lattice','chrome',3,'Armor +3; movement consumes extra hydration.'],['reflex','Reflex accelerator','chrome',3,'Every fourth enemy turn is skipped.'],['muscle','Servo musculature','chrome',3,'Melee damage +5; capacity +10.'],['jack','Neural jack','chrome',2,'Hacking checks +3; Echo exposure grows at night.'],['lung','Filtered lungs','chrome',2,'Immune to poison, infection and toxic terrain.'],['storage','Abdominal vault','chrome',1,'Capacity +18.'],['heart','Second heart','flesh',3,'Survive one fatal blow per run with 35 HP.'],['gills','Marsh gills','flesh',2,'Toxic tiles heal you; water restores extra nutrition.'],['skin','Chitin graft','flesh',3,'Armor +4; social checks -2.'],['tendon','Elastic tendons','flesh',2,'Move twice with Dash; stealth +2.'],['blood','Red garden','flesh',3,'Heal 1 HP every 4 turns, consuming nutrition.']
].forEach(([id,n,t,strain,desc])=>item(id,n,t,0.3,90+strain*20,{strain,desc}));
const factions=[
 {id:'union',name:'Lamplighter Union',color:'#edb86f',enemy:'crown',goal:'Keep the pumps running. Get the families out.',benefit:'Safe beds, industrial salvage, the evacuation train.'},
 {id:'crown',name:'Glass Directorate',color:'#71bed9',enemy:'union',goal:'Preserve the archive, even if the streets must be abandoned.',benefit:'Firearms, security clearances, corporate extraction.'},
 {id:'garden',name:'Red Garden',color:'#d38c9a',enemy:'choir',goal:'Let the body adapt to the city instead of replacing it.',benefit:'Medicine, biological grafts, protection from contamination.'},
 {id:'choir',name:'The Quiet Choir',color:'#ad9ee7',enemy:'garden',goal:'Listen to the people still speaking through the dead network.',benefit:'Neural Chrome, signal lore, the impossible door.'}
];
const zones=[
 {name:'Lowlight Blocks',sub:'A neighborhood that remembers you',kind:'Sanctuary / streets',color:'#69cbb1',wall:'#243c3a',floor:'#111e22',faction:'union',danger:1,layout:'blocks',building:['Apartment','Corner store','Utility room'],npc:'Mara Venn',voice:'I keep a light on for anyone who comes back. Don’t make me waste the oil.',objective:'Restore the neighborhood pump',object:'Pressure regulator',story:'The regulator is wrapped in a child’s scarf. Someone tried to keep the machine warm.',loot:['food','water','cloth','scrap','bandage'],enemies:['rat','looter'],links:[1,2]},
 {name:'Mercy Arcade',sub:'Everything has a price, even mercy',kind:'Expedition / ruined mall',color:'#deb46f',wall:'#443932',floor:'#241d1b',faction:'garden',danger:2,layout:'mall',building:['Pharmacy','Food court','Shuttered boutique'],npc:'Dr. Iona Reed',voice:'Chrome does not dream. Flesh does. I haven’t decided which is kinder.',objective:'Recover cold-chain medicine',object:'Cryogenic insulin case',story:'The freezer still works. The names on its doors belong to people outside.',loot:['medkit','chemical','food','antidote','scrubs'],enemies:['looter','hound'],links:[0,3,4]},
 {name:'Rainline Viaduct',sub:'The last trains ran without drivers',kind:'Travel / rooftops',color:'#73a9cc',wall:'#29394c',floor:'#121c2c',faction:'union',danger:2,layout:'rail',building:['Signal box','Maintenance bay','Worker dormitory'],npc:'Old Brin',voice:'Tracks don’t care who owns the station. They just need someone to throw the switch.',objective:'Recover the rail ignition core',object:'Ignition core',story:'Its last diagnostic reads: PASSENGERS STILL ABOARD. The train has been empty for years.',loot:['scrap','circuit','ammo','repair','wrench'],enemies:['sniper','drone'],links:[0,3,5]},
 {name:'Cinderworks',sub:'The furnaces are hungry again',kind:'Expedition / foundry',color:'#e28b68',wall:'#49322b',floor:'#281915',faction:'union',danger:3,layout:'factory',building:['Smelter','Tool cage','Boiler room'],npc:'Tess Kiln',voice:'The Directorate wants my generators. The Union wants my hands. What do you want?',objective:'Secure the turbine assembly',object:'Turbine assembly',story:'The turbine could power the train, or a thousand apartment lights. Not both.',loot:['scrap','repair','grenade','hammer','flamer'],enemies:['brute','drone','looter'],links:[1,2,6]},
 {name:'Suture Ward',sub:'Roots under the operating theater',kind:'Expedition / hospital',color:'#bb92a8',wall:'#3e303d',floor:'#221923',faction:'garden',danger:3,layout:'hospital',building:['Operating room','Patient ward','Research lab'],npc:'Sister Vale',voice:'There is no such thing as an unmodified human. Only modifications you have stopped noticing.',objective:'Rescue the sealed-ward survivor',object:'A survivor called Neri',story:'Neri remembers your face from a dream. They have never left this room.',loot:['medkit','antidote','chemical','bandage','blood'],enemies:['feral','hound'],links:[1,6,7]},
 {name:'Glass Meridian',sub:'The upper floors still have electricity',kind:'Expedition / corporate archive',color:'#85c9db',wall:'#2b404d',floor:'#14232d',faction:'crown',danger:4,layout:'office',building:['Security office','Executive suite','Server room'],npc:'Auditor Sable',voice:'The manifest has room for one more. I can’t promise what you’ll be asked to leave behind.',objective:'Acquire the evacuation manifest',object:'Signed evacuation manifest',story:'The names of the dead have been erased. Your name is already at the bottom.',loot:['ammo','data','circuit','pistol','scope'],enemies:['guard','sniper','drone'],links:[2,6,7]},
 {name:'Drowned Exchange',sub:'The water carries voices',kind:'Travel / utility tunnels',color:'#77bfa4',wall:'#254439',floor:'#13271f',faction:'choir',danger:4,layout:'tunnels',building:['Flood pump','Cable vault','Submerged platform'],npc:'Nine',voice:'Eight of us stopped answering. I’m still here. That is how I chose my name.',objective:'Extract the submerged memory spool',object:'Memory spool',story:'The recording is of rain, a door opening, and your own voice saying: not this time.',loot:['circuit','data','water','battery','jack'],enemies:['feral','wraith','drone'],links:[3,4,5,7]},
 {name:'The Listening Spire',sub:'It has been waiting for you',kind:'Final expedition / signal tower',color:'#b5a2e3',wall:'#393048',floor:'#1e172e',faction:'choir',danger:5,layout:'spire',building:['Memory chamber','Relay gallery','Observation room'],npc:'The Operator',voice:'You have reached this room before. Or someone very much like you. Does the distinction help?',objective:'Tune the impossible broadcast',object:'The unbroken frequency',story:'Between two stations is a door. Behind the door is the sound of a city that never broke.',loot:['battery','data','circuit','railgun','eyes'],enemies:['wraith','guard','drone'],links:[4,5,6]}
];
const enemies={
 rat:{name:'Cable vermin',hp:13,damage:4,armor:0,range:1,ai:'rush',glyph:'r',color:'#bdaf8c',xp:12},
 looter:{name:'Hungry scavenger',hp:22,damage:6,armor:1,range:1,ai:'coward',glyph:'s',color:'#cd9875',xp:20},
 hound:{name:'Grafted hound',hp:25,damage:7,armor:1,range:1,ai:'flank',glyph:'h',color:'#df8791',xp:24,bleed:true},
 drone:{name:'Civic drone',hp:24,damage:6,armor:2,range:5,ai:'ranged',glyph:'d',color:'#79bdda',xp:28,machine:true},
 sniper:{name:'Roofline marksman',hp:25,damage:10,armor:1,range:8,ai:'ranged',glyph:'s',color:'#e5b56c',xp:34},
 brute:{name:'Furnace breaker',hp:48,damage:11,armor:3,range:1,ai:'guard',glyph:'B',color:'#e98b65',xp:44},
 feral:{name:'Bloom carrier',hp:35,damage:8,armor:2,range:1,ai:'flank',glyph:'f',color:'#c896b9',xp:34,poison:true},
 guard:{name:'Directorate sentinel',hp:42,damage:10,armor:4,range:6,ai:'ranged',glyph:'G',color:'#9fcee3',xp:50,faction:'crown'},
 wraith:{name:'An echo of someone',hp:33,damage:11,armor:0,range:3,ai:'rush',glyph:'e',color:'#b4a2ea',xp:48,echo:true}
};
const talentDefs=[
 ['wayfinder','Service maps','Open ducts between districts; +2 sight.','Ghost','kid'],['ambush','Knife in the dark','Hidden attacks deal double damage.','Ghost','kid'],['fade','Nobody home','Slipstream lasts twice as long.','Ghost','kid'],['broker','Everybody owes','Shop prices -30%; social checks +3.','Fixer','kid'],['cache','Hidden pockets','Scavenge twice as many supplies; +10 capacity.','Fixer','kid'],['friends','Old friends','Gain 15 reputation with every faction.','Fixer','kid'],
 ['bulwark','Hold the line','Gain +3 armor when not sneaking.','Bastion','soldier'],['veteran','Scar tissue','Maximum HP +25.','Bastion','soldier'],['rebound','Return fire','Taking ranged damage charges 5 energy.','Bastion','soldier'],['aim','One clean shot','Ranged attacks ignore 3 armor.','Deadeye','soldier'],['conserve','Hand-loaded','Every other shot uses no ammunition.','Deadeye','soldier'],['killchain','Kill chain','Kills recover 10 energy and 6 HP.','Deadeye','soldier'],
 ['rewrite','Change of owner','Blackout converts the closest drone permanently.','Puppeteer','hacker'],['leech','Current thief','Machine kills restore 20 energy.','Puppeteer','hacker'],['overload','Overload','Blackout also deals 18 damage to machines.','Puppeteer','hacker'],['skeleton','Skeleton key','Sealed caches open without a check.','Architect','hacker'],['cartography','Network cartographer','Entering a district reveals its map, but not occupants.','Architect','hacker'],['efficiency','Low-power mode','Class abilities cost half energy.','Architect','hacker'],
 ['field','Field surgery','Medical items heal twice as much.','Lifeline','medic'],['resolve','Do no harm','Triage also fills energy and reduces fatigue.','Lifeline','medic'],['mercy','Second chances','Rescuing Neri awards all factions +15 reputation.','Lifeline','medic'],['venom','Dirty instruments','Melee attacks inflict poison.','Plaguehand','medic'],['immune','Adaptive immune system','Immune to poison, infection and bleeding.','Plaguehand','medic'],['harvest','Living samples','Kills grant a reagent vial and restore 3 HP.','Plaguehand','medic'],
 ['turret','Hardened sentry','Sentry lasts 20 turns and deals +5 damage.','Machinist','engineer'],['recycler','Closed loop','Salvaging equipment yields circuits.','Machinist','engineer'],['rigging','Loadmaster','Capacity +20 and repairs cost no scrap.','Machinist','engineer'],['blast','Shaped charges','Grenades deal 42 damage and spare allies.','Demolitionist','engineer'],['breach','Breach doctrine','Locked objectives can be forced without injury.','Demolitionist','engineer'],['powder','Waste nothing','Craft ammunition and grenades at half cost.','Demolitionist','engineer'],
 ['listen','Listen closely','Each objective grants an extra Echo fragment.','Witness','sensitive'],['lucid','Lucid signal','Echo exposure no longer causes damage.','Witness','sensitive'],['chorus','Friendly frequency','Wraiths ignore you unless attacked.','Witness','sensitive'],['phase','Thin places','Walk through one-tile walls for 5 energy.','Hollow','sensitive'],['scream','Dead air','Resonance deals 28 damage.','Hollow','sensitive'],['devour','Borrowed lives','Resonance heals 5 HP per enemy struck.','Hollow','sensitive']
];
const talents=talentDefs.map(([id,name,desc,path,cls],i)=>({id,name,desc,path,cls,tier:i%3+1}));
const recipes=[{id:'bandage',n:2,cost:{cloth:2}},{id:'medkit',n:1,cost:{cloth:2,chemical:2}},{id:'ammo',n:12,cost:{scrap:3,chemical:1}},{id:'grenade',n:1,cost:{scrap:3,chemical:2}},{id:'repair',n:1,cost:{scrap:3,cloth:1}},{id:'battery',n:1,cost:{scrap:2,circuit:1}},{id:'smoke',n:1,cost:{cloth:1,chemical:1}},{id:'antidote',n:1,cost:{chemical:2}},{id:'crossbow',n:1,cost:{scrap:8,cloth:3}},{id:'edge',n:1,cost:{scrap:6,circuit:1}}];
root.NRData={classes,items,factions,zones,enemies,talents,recipes};
if(typeof module!=='undefined')module.exports=root.NRData;
})(typeof window!=='undefined'?window:globalThis);
