(function(root){
'use strict';
const D=root.NRData||(typeof require!=='undefined'?require('./data.js'):null);
const dist=(a,b)=>Math.max(Math.abs(a.x-b.x),Math.abs(a.y-b.y));
const dirs=[[0,-1],[1,0],[0,1],[-1,0],[1,1],[-1,1],[1,-1],[-1,-1]];
class Game{
 constructor(state){this.s=state||null;this.onchange=()=>{};this.prompt=null;this.effects=[];this.visible=new Set();if(state)this.vision();}
 rand(){let x=this.s.rng|0;x^=x<<13;x^=x>>>17;x^=x<<5;this.s.rng=x>>>0;return (x>>>0)/4294967296;}
 pick(a){return a[Math.floor(this.rand()*a.length)];}
 int(a,b){return a+Math.floor(this.rand()*(b-a+1));}
 newRun(name,cls,seed){let hash=2166136261;for(const c of String(seed||Date.now()))hash=Math.imul(hash^c.charCodeAt(0),16777619);const c=D.classes.find(c=>c.id===cls)||D.classes[0];
  this.s={version:1,seed:String(seed||hash>>>0),rng:hash>>>0||1,turn:0,time:18*60,zone:0,maps:{},rep:{union:8,crown:0,garden:0,choir:0},quests:{},flags:{},log:[],history:[],weather:'Rain',nextId:1,ending:null,kills:0,scavenged:0,visited:[0],p:{name:(name||'Ash').slice(0,24),cls:c.id,x:4,y:4,stats:[...c.stats],hp:55+c.stats[2]*5,maxHp:55+c.stats[2]*5,energy:50,maxEnergy:50,food:90,water:90,fatigue:0,xp:0,level:1,points:1,credits:65,inventory:[],weapon:null,armor:null,gear:null,talents:[],augments:[],status:{},cooldown:0,sneak:false,echo:0,fragments:0,specialization:null}};
  this.add(c.weapon);this.s.p.weapon=this.s.p.inventory.at(-1).uid;this.add(c.armor);this.s.p.armor=this.s.p.inventory.at(-1).uid;this.add('pack');this.s.p.gear=this.s.p.inventory.at(-1).uid;
  this.add('food',4);this.add('water',4);this.add('bandage',3);this.add('medkit',2);this.add('ammo',c.id==='soldier'?36:16);this.add('scrap',5);this.add('circuit',2);this.add('cloth',3);this.add('chemical',2);if(c.id==='hacker')this.add('pistol');
  this.s.maps[0]=this.generate(0);this.s.p.x=this.map.start.x;this.s.p.y=this.map.start.y;this.log('You wake beneath a flickering sign. Mara’s shelter is one step east. The city exhales.','story');this.log('Move with WASD / arrows. Bump enemies to attack. E interacts. Nothing moves until you do.','hint');this.vision();this.changed();return this.s;
 }
 get p(){return this.s.p;}get map(){return this.s.maps[this.s.zone];}get night(){let h=(this.s.time/60)%24;return h>=19||h<6;}get day(){return Math.floor(this.s.time/1440)+1;}
 has(id){return this.p.talents.includes(id)||this.p.augments.includes(id);}
 equipped(slot){return this.p.inventory.find(i=>i.uid===this.p[slot]);}
 equipment(slot){const i=this.equipped(slot);return i?{...D.items[i.id],...i}:null;}
 count(id){return this.p.inventory.filter(i=>i.id===id).reduce((n,i)=>n+i.qty,0);}
 add(id,qty=1){const d=D.items[id];if(!d)return false;const stack=!['weapon','armor','gear'].includes(d.type);const i=stack&&this.p.inventory.find(i=>i.id===id);if(i)i.qty+=qty;else this.p.inventory.push({uid:this.s.nextId++,id,qty,durability:d.durability||0,mods:[]});return true;}
 take(id,n=1){if(this.count(id)<n)return false;for(const i of [...this.p.inventory])if(i.id===id){let q=Math.min(n,i.qty);i.qty-=q;n-=q;if(!i.qty){this.p.inventory.splice(this.p.inventory.indexOf(i),1);for(const s of ['weapon','armor','gear'])if(this.p[s]===i.uid)this.p[s]=null;}if(n===0)break;}return true;}
 weight(){return this.p.inventory.reduce((n,i)=>n+D.items[i.id].weight*i.qty,0);}
 capacity(){return 20+this.p.stats[0]*3+(this.equipment('gear')?.capacity||0)+(this.has('storage')?18:0)+(this.has('muscle')?10:0)+(this.has('rigging')?20:0)+(this.has('cache')?10:0);}
 armor(){return (this.equipment('armor')?.armor||0)+(this.has('dermal')?3:0)+(this.has('skin')?4:0)+(this.has('bulwark')&&!this.p.sneak?3:0);}
 check(type){const a={force:0,stealth:1,endure:2,scout:3,hack:4,social:5};return this.p.stats[a[type]]+(type==='hack'&&this.has('jack')?3:0)+(type==='social'&&this.has('broker')?3:0)-(type==='social'&&this.has('skin')?2:0);}
 log(text,type='normal'){this.s.log.push({text,type,turn:this.s.turn});if(this.s.log.length>100)this.s.log.shift();if(type==='story')this.s.history.push({text,day:this.day});}
 changed(){this.onchange(this);}
 tile(x,y){if(x<0||y<0||x>=this.map.w||y>=this.map.h)return '#';return this.map.tiles[y*this.map.w+x];}
 walk(x,y){return !['#','+'].includes(this.tile(x,y));}
 los(a,b){let x=a.x,y=a.y,dx=Math.abs(b.x-x),dy=-Math.abs(b.y-y),sx=x<b.x?1:-1,sy=y<b.y?1:-1,err=dx+dy;while(x!==b.x||y!==b.y){let e=2*err;if(e>=dy){err+=dy;x+=sx;}if(e<=dx){err+=dx;y+=sy;}if(x===b.x&&y===b.y)return true;if(['#','+'].includes(this.tile(x,y)))return false;}return true;}
 vision(){if(!this.s)return;this.visible=new Set();const r=(this.night?6:9)+Math.floor(this.p.stats[3]/3)+(this.has('eyes')?3:0)+(this.has('wayfinder')?2:0)-(this.map.blackout>this.s.turn?2:0)-(this.s.weather==='Low fog'?2:0)-(this.p.status.concussion>0?2:0);for(let y=Math.max(0,this.p.y-r);y<=Math.min(this.map.h-1,this.p.y+r);y++)for(let x=Math.max(0,this.p.x-r);x<=Math.min(this.map.w-1,this.p.x+r);x++)if(Math.hypot(x-this.p.x,y-this.p.y)<=r&&this.los(this.p,{x,y})){let k=y*this.map.w+x;this.visible.add(k);this.map.seen[k]=1;}}
 seen(e){return this.visible.has(e.y*this.map.w+e.x);}
 generate(z){const d=D.zones[z],w=44,h=32,m={w,h,tiles:Array(w*h).fill('#'),seen:Array(w*h).fill(0),entities:[],rooms:[],start:{x:5,y:5},cleared:false,blackout:0};
  const put=(x,y,t)=>{if(x>0&&y>0&&x<w-1&&y<h-1)m.tiles[y*w+x]=t;};
  // Nine urban room templates, linked by a traversable service network.
  for(let ry=0;ry<3;ry++)for(let rx=0;rx<3;rx++){const x=2+rx*14+this.int(0,1),y=2+ry*10,ww=this.int(9,11),hh=this.int(6,8);let r={x,y,w:ww,h:hh,cx:x+Math.floor(ww/2),cy:y+Math.floor(hh/2),name:d.building[(rx+ry)%3]};m.rooms.push(r);for(let yy=y;yy<y+hh;yy++)for(let xx=x;xx<x+ww;xx++)put(xx,yy,'.');}
  const carve=(a,b)=>{let x=a.cx,y=a.cy;while(x!==b.cx){put(x,y,'.');x+=Math.sign(b.cx-x);}while(y!==b.cy){put(x,y,'.');y+=Math.sign(b.cy-y);}put(x,y,'.');};
  for(let i=0;i<9;i++){if(i%3<2)carve(m.rooms[i],m.rooms[i+1]);if(i<6&&(d.layout!=='tunnels'||i%3===(Math.floor(i/3)%2?2:0))&&(d.layout!=='rail'||i%3!==1)&&(d.layout!=='spire'||i%3!==1))carve(m.rooms[i],m.rooms[i+3]);}
  if(d.layout==='mall'){for(let y=13;y<=17;y++)for(let x=2;x<42;x++)put(x,y,'.');}
  if(d.layout==='rail'){for(let x=2;x<42;x++){put(x,11,'.');put(x,21,'.');}for(const r of m.rooms)for(let y=r.cy;y<=Math.min(29,r.cy+5);y++)put(r.cx,y,'.');}
  if(['hospital','office'].includes(d.layout))for(const r of m.rooms.slice(1)){const split=r.x+3;for(let y=r.y;y<r.y+r.h;y++)put(split,y,y===r.cy?'+':'#');put(split,r.y+1,'+');}
  if(d.layout==='factory')for(const r of m.rooms.slice(1)){put(r.x+2,r.y+2,'!');put(r.x+3,r.y+2,'!');put(r.x+2,r.y+3,'=');}
  if(d.layout==='spire')for(const r of m.rooms.slice(1)){put(r.x+2,r.y+2,'#');put(r.x+r.w-3,r.y+2,'#');put(r.x+2,r.y+r.h-3,'#');put(r.x+r.w-3,r.y+r.h-3,'#');}
  m.start={x:m.rooms[0].cx-2,y:m.rooms[0].cy};
  const occupied=(x,y)=>m.entities.some(e=>e.x===x&&e.y===y);
  const entity=(type,x,y,p={})=>{let e={uid:this.s.nextId++,type,x,y,...p};m.entities.push(e);return e;};
  const spot=(r)=>{for(let tries=0;tries<100;tries++){let x=this.int(r.x+1,r.x+r.w-2),y=this.int(r.y+1,r.y+r.h-2);if(m.tiles[y*w+x]==='.'&&!occupied(x,y)&&dist({x,y},m.start)>1)return{x,y};}return{x:r.cx,y:r.cy};};
  // Furniture, doors and hazards differ by district; central corridors remain clear.
  m.rooms.forEach((r,i)=>{if(i>0){for(let k=0;k<4;k++){let p=spot(r);if(p.x!==r.cx&&p.y!==r.cy)put(p.x,p.y,(z===6||z===4)?'~':z===3?'!':'=');}let dx=r.x-1,dy=r.cy;if(m.tiles[dy*w+dx]==='.')put(dx,dy,'+');}
   for(let k=0;k<(i?2:1);k++){let p=spot(r);entity('cache',p.x,p.y,{name:r.name+' locker',pool:(r.name==='Pharmacy'||r.name==='Operating room')?['medkit','bandage','chemical']:d.loot,locked:i>3&&this.rand()<0.35,hidden:this.rand()<0.14,opened:false});}
  });
  entity('npc',m.start.x+1,m.start.y,{name:d.npc,faction:d.faction,zone:z});entity('bed',m.start.x,m.start.y+1,{name:'Shelter cot'});entity('bench',m.start.x-1,m.start.y+1,{name:'Community workbench'});
  const exits=[2,6,3,1];d.links.forEach((to,i)=>{let p=spot(m.rooms[exits[i]]);entity('gate',p.x,p.y,{to,name:'Route to '+D.zones[to].name});});
  let p=spot(m.rooms[8]);entity('objective',p.x,p.y,{zone:z,name:d.object,done:false});
  let bossSpot=spot(m.rooms[8]);const bossBase=D.enemies[d.enemies.at(-1)];entity('enemy',bossSpot.x,bossSpot.y,{...bossBase,key:d.enemies.at(-1),name:['The Rent Collector','Mercy’s Watchdog','Trackwarden','The Furnace Heart','Patient Zero','Chief of Security','The Drowned Voice','The Last Receiver'][z],hp:bossBase.hp+15+z*4,maxHp:bossBase.hp+15+z*4,damage:bossBase.damage+2,boss:true,xp:80+z*15,alert:0,status:{}});
  for(let i=0;i<8+z*2;i++){let r=this.pick(m.rooms.slice(1)),p=spot(r),key=this.pick(d.enemies),base=D.enemies[key];entity('enemy',p.x,p.y,{...base,key,hp:base.hp+z*2,maxHp:base.hp+z*2,alert:0,status:{}});}
  let ev=spot(m.rooms[4]);entity('event',ev.x,ev.y,{name:this.pick(['A wounded courier','A voice in the terminal','A barricaded family','An unclaimed shipment']),done:false});
  let duct=spot(m.rooms[5]);entity('duct',duct.x,duct.y,{name:'Unmarked service duct',to:(z+2)%8});
  if(z===2||z===5||z===7){let p=spot(m.rooms[7]);entity('escape',p.x,p.y,{name:z===2?'The last train':z===5?'Corporate landing pad':'The impossible door',route:z===2?'train':z===5?'air':'echo'});}
  if(this.has('cartography'))m.seen.fill(1);return m;
 }
 nearby(type){return this.map.entities.filter(e=>e.type===type&&dist(e,this.p)<=1);}
 safe(){return this.nearby('bed').length>0&&this.s.rep[D.zones[this.s.zone].faction]>-20;}
 enemyAt(x,y){return this.map.entities.find(e=>e.type==='enemy'&&e.hp>0&&e.x===x&&e.y===y&&!e.ally);}
 living(){return this.map.entities.filter(e=>e.type==='enemy'&&e.hp>0);}
 move(dx,dy){if(this.s.ending)return;const x=this.p.x+dx,y=this.p.y+dy;if(dx&&dy&&(!this.walk(this.p.x+dx,this.p.y)||!this.walk(this.p.x,this.p.y+dy)))return;
  let e=this.enemyAt(x,y);if(e){this.attack(e);return;}
  if(this.tile(x,y)==='+'){this.map.tiles[y*this.map.w+x]='.';this.log('You ease open a warped door.');this.tick();return;}
  if(this.tile(x,y)==='#'&&this.has('phase')&&this.p.energy>=5&&this.walk(x+dx,y+dy)&&!this.enemyAt(x+dx,y+dy)){this.p.x=x+dx;this.p.y=y+dy;this.p.energy-=5;this.p.echo+=1;this.tick();return;}
  if(!this.walk(x,y))return;const npc=this.map.entities.find(e=>e.type==='npc'&&e.x===x&&e.y===y);if(npc){this.interact(npc);return;}
  this.p.x=x;this.p.y=y;this.tick();
 }
 attack(e){if(this.s.ending||!e||e.hp<=0)return;const w=this.equipment('weapon')||{name:'Bare hands',damage:2,range:1},range=w.range+(w.mods?.includes('scope')?2:0);if(!this.seen(e)||!this.los(this.p,e)||dist(e,this.p)>range){this.log('No clear shot within weapon range.','hint');this.changed();return;}
  if(w.ammo&&this.count('ammo')<w.ammo){this.log('No ammunition. Equip a melee weapon or craft cartridges.','bad');this.changed();return;}
  if(w.ammo&&!(this.has('conserve')&&this.s.turn%2===0))this.take('ammo',w.ammo);
  let damage=w.damage+(w.mods?.includes('edge')?3:0)+Math.floor(this.p.stats[w.range>2?3:0]/2)+(this.has('muscle')&&w.range<=2?5:0);if(w.durability<20&&w.uid)damage=Math.floor(damage*0.6);
  const hidden=this.p.status.hidden>0||(this.p.sneak&&!e.alert);if(hidden)damage=Math.floor(damage*(this.has('ambush')?2:1.4));
  let cover=this.tile(e.x,e.y)==='='&&w.range>2?3:0;damage=Math.max(1,damage-(this.p.fatigue>80?3:0)-this.int(0,2)-Math.max(0,e.armor-(w.pierce||0)-(this.has('aim')&&w.range>2?3:0))-cover);
  this.hurtEnemy(e,damage);this.effects.push({type:'attack',x:e.x,y:e.y,from:{x:this.p.x,y:this.p.y},value:damage});
  if(e.hp>0){if(w.bleed&&this.rand()<w.bleed)e.status.bleeding=4;if(w.stun&&this.rand()<w.stun)e.status.stun=2;if(w.burn)e.status.burn=3;if(this.has('venom')&&w.range<=2)e.status.poison=5;e.alert=10;}
  if(w.spread)for(const other of this.living())if(other!==e&&dist(other,e)<=1&&!other.ally)this.hurtEnemy(other,Math.floor(damage/2));
  if(w.uid)this.equipped('weapon').durability=Math.max(0,this.equipped('weapon').durability-0.6);
  const noise=(w.noise||2)-(w.mods?.includes('silencer')?6:0);for(const n of this.living())if(dist(n,this.p)<noise)n.alert=10;this.p.status.hidden=0;this.tick();
 }
 hurtEnemy(e,n){e.hp-=n;this.log(`${e.name} takes ${n} damage.`,'combat');if(e.hp<=0){this.s.kills++;this.gainXp(e.xp);this.p.credits+=this.int(3,9);this.log(`${e.name} falls.${e.boss?' The district’s guardian is gone.':''}`,e.boss?'story':'good');if(e.boss){this.map.cleared=true;this.add(this.pick(['medkit','ammo','data','repair']),e.key==='drone'?2:1);}if(this.has('killchain')){this.p.energy=Math.min(this.p.maxEnergy,this.p.energy+10);this.heal(6);}if(this.has('leech')&&e.machine)this.p.energy=Math.min(this.p.maxEnergy,this.p.energy+20);if(this.has('harvest')){this.add('chemical');this.heal(3);}if(this.rand()<0.45)this.add(e.machine?'scrap':'ammo',e.machine?2:3);}}
 heal(n){this.p.hp=Math.min(this.p.maxHp,this.p.hp+n);}
 damage(n,cause,status){this.p.hp-=Math.max(0,n);if(status&&!this.has('immune')&&!((status==='poison'||status==='infection')&&this.has('lung')))this.p.status[status]=Math.max(this.p.status[status]||0,7);if(this.p.hp<=0){if(this.has('heart')&&!this.s.flags.heartUsed){this.s.flags.heartUsed=true;this.p.hp=35;this.log('Your second heart tears itself apart to keep the first one beating.','story');}else this.finish('death',cause);}}
 gainXp(n){this.p.xp+=n;let need=this.p.level*65;while(this.p.xp>=need){this.p.xp-=need;this.p.level++;this.p.points++;this.p.maxHp+=5;this.heal(15);this.p.maxEnergy+=3;this.p.energy=this.p.maxEnergy;this.log(`Level ${this.p.level}. A new talent point. You are becoming someone else.`,'good');need=this.p.level*65;}}
 tick(n=1,rest=false){for(let k=0;k<n&&!this.s.ending;k++){
  this.s.turn++;this.s.time+=5;const p=this.p;p.energy=Math.min(p.maxEnergy,p.energy+(p.sneak?0.55:0.9));p.food=Math.max(0,p.food-(this.has('blood')?0.16:0.09));p.water=Math.max(0,p.water-(this.has('dermal')?0.18:0.12));p.fatigue=Math.min(100,p.fatigue+(rest?0:0.1)+(this.weight()>this.capacity()?0.2:0));if(p.cooldown>0)p.cooldown--;
  if(!rest){for(const s of ['bleeding','poison','burn','infection'])if(p.status[s]>0){this.damage(s==='infection'?1:2,s);p.status[s]--;}
   if(this.tile(p.x,p.y)==='!')this.damage(3,'a foundry fire','burn');if(this.tile(p.x,p.y)==='~'){if(this.has('gills'))this.heal(2);else if(!this.has('lung')&&(this.equipment('armor')?.resist||0)<3)this.damage(2,'toxic runoff','poison');}
   if(this.s.turn%6===0&&(p.food<=0||p.water<=0||p.fatigue>=100))this.damage(3,'exhaustion and deprivation');
  }
  if(this.has('blood')&&this.s.turn%4===0&&p.food>10)this.heal(1);if(this.equipment('armor')?.regen&&this.s.turn%6===0)this.heal(1);if(this.s.weather==='Acid rain'&&this.s.turn%6===0&&!this.map.rooms.some(r=>p.x>=r.x&&p.x<r.x+r.w&&p.y>=r.y&&p.y<r.y+r.h)&&!(this.equipment('armor')?.resist))this.damage(1,'acid rain');
  for(const s of ['hidden','overwatch','fracture','concussion'])if(p.status[s]>0)p.status[s]--;
  if(this.has('jack')&&this.night&&this.s.turn%15===0)p.echo++;
  const strain=p.augments.reduce((n,id)=>n+D.items[id].strain,0);if(strain>7&&this.s.turn%10===0){p.energy=Math.max(0,p.energy-(strain-7)*2);if(p.energy===0)this.damage(2,'augmentation rejection');}
  if(p.echo>=65&&this.s.turn%12===0&&!this.has('lucid')){this.damage(2,'signal overload');this.log('A voice inside your skull counts your teeth.','bad');}
  this.vision();if(!rest&&!this.s.ending){this.ai();this.sentry();}if(this.s.turn%48===0&&!rest)this.worldEvent();
 }this.vision();this.changed();}
 ai(){if(this.has('reflex')&&this.s.turn%4===0)return;for(const e of this.living()){
  if(this.s.ending)return;if(e.status.stun>0){e.status.stun--;continue;}for(const s of ['bleeding','poison','burn'])if(e.status[s]>0){e.status[s]--;this.hurtEnemy(e,2);}if(e.hp<=0)continue;
  if(e.ally){let target=this.living().filter(n=>!n.ally&&dist(e,n)<=6&&this.los(e,n)).sort((a,b)=>dist(e,a)-dist(e,b))[0];if(target)this.hurtEnemy(target,6);continue;}
  if(e.echo&&this.has('chorus')&&!e.alert)continue;if(e.faction&&this.s.rep[e.faction]>=15&&!e.alert)continue;
  let d=dist(e,this.p),vision=(this.night?5:8)-(this.p.sneak?2+Math.floor(this.p.stats[1]/3):0)-(this.equipment('armor')?.stealth||0)-(this.has('tendon')?2:0);if(this.p.status.hidden>0)vision=1;
  if(d<=Math.max(1,vision)&&this.los(e,this.p)){e.alert=8;e.target={x:this.p.x,y:this.p.y};}else if(e.alert>0)e.alert--;
  if(e.alert>0&&d<=e.range&&this.los(e,this.p)&&(this.p.status.hidden<=0||d<=1||!this.p.status.hidden)){
   if(e.ai==='ranged'&&d<=2&&this.rand()<0.6){this.stepEnemy(e,{x:e.x+(e.x-this.p.x),y:e.y+(e.y-this.p.y)});continue;}
   let dodge=(this.p.stats[1]+(this.equipment('armor')?.agility||0))*0.025+(this.p.sneak?0.05:0);if(this.rand()<dodge){this.log(`You evade ${e.name}.`,'good');continue;}
   let dmg=Math.max(1,e.damage+this.int(-2,2)-this.armor()-(this.tile(this.p.x,this.p.y)==='='&&e.range>1?3:0));this.damage(dmg,e.name,e.bleed?'bleeding':e.poison?'poison':e.echo?'concussion':undefined);this.effects.push({type:'hurt',x:this.p.x,y:this.p.y,value:dmg});this.log(`${e.name} hits you for ${dmg}.`,'bad');if(this.has('rebound')&&e.range>1)this.p.energy=Math.min(this.p.maxEnergy,this.p.energy+5);if(e.echo)this.p.echo+=1;
  }else if(e.alert>0){let target=e.target||this.p;if(e.ai==='coward'&&e.hp<e.maxHp/3)target={x:e.x+(e.x-this.p.x),y:e.y+(e.y-this.p.y)};this.stepEnemy(e,target,e.ai==='flank');}else if(e.ai!=='guard'&&this.s.turn%3===0){let [dx,dy]=this.pick(dirs);this.stepEnemy(e,{x:e.x+dx,y:e.y+dy});}
 }if(this.p.status.overwatch>0){let e=this.living().find(e=>!e.ally&&this.seen(e)&&dist(e,this.p)<=9&&this.los(e,this.p));if(e&&this.count('ammo')){this.take('ammo');this.hurtEnemy(e,10+Math.floor(this.p.stats[3]/2));}}}
 stepEnemy(e,target,flank=false){let opts=dirs.map(([dx,dy])=>({x:e.x+dx,y:e.y+dy,dx,dy})).filter(p=>this.walk(p.x,p.y)&&!(p.dx&&p.dy&&(!this.walk(e.x+p.dx,e.y)||!this.walk(e.x,e.y+p.dy)))&&!this.living().some(n=>n!==e&&n.x===p.x&&n.y===p.y)&&!(p.x===this.p.x&&p.y===this.p.y)&&dist(p,this.map.start)>3);opts.sort((a,b)=>dist(a,target)-dist(b,target));if(opts.length){let p=opts[flank&&opts.length>1&&this.s.turn%3===0?1:0];e.x=p.x;e.y=p.y;}}
 sentry(){for(const e of this.map.entities.filter(e=>e.type==='sentry'&&e.life>0)){e.life--;let t=this.living().find(t=>!t.ally&&dist(e,t)<=6&&this.los(e,t));if(t)this.hurtEnemy(t,this.has('turret')?12:7);}}
 ability(){if(this.s.ending)return;if(this.p.cooldown){this.log(`Ability ready in ${this.p.cooldown} turns.`,'hint');this.changed();return;}let cost=this.p.cls==='medic'?16:14;if(this.has('efficiency'))cost/=2;if(this.p.energy<cost){this.log('Not enough energy. Rest, wait, or use a battery.','bad');this.changed();return;}this.p.energy-=cost;this.p.cooldown=10;const c=this.p.cls;
  if(c==='kid'){this.p.status.hidden=this.has('fade')?11:6;this.p.energy=Math.min(this.p.maxEnergy,this.p.energy+12);for(const e of this.living())e.alert=0;}
  if(c==='soldier')this.p.status.overwatch=6;
  if(c==='hacker'){let converted=false;for(const e of this.living().filter(e=>this.seen(e)&&!e.ally)){e.status.stun=e.machine?7:3;if(e.machine&&this.has('rewrite')&&!converted){e.ally=true;converted=true;}if(e.machine&&this.has('overload'))this.hurtEnemy(e,18);}for(let y=this.p.y-7;y<=this.p.y+7;y++)for(let x=this.p.x-7;x<=this.p.x+7;x++)if(x>=0&&y>=0&&x<this.map.w&&y<this.map.h)this.map.seen[y*this.map.w+x]=1;}
  if(c==='medic'){this.heal(26);this.p.status={};if(this.has('resolve')){this.p.energy=this.p.maxEnergy;this.p.fatigue=Math.max(0,this.p.fatigue-20);}}
  if(c==='engineer')this.map.entities.push({uid:this.s.nextId++,type:'sentry',x:this.p.x,y:this.p.y,life:this.has('turret')?21:11,name:'Scrap sentry'});
  if(c==='sensitive'){for(const e of this.living().filter(e=>!e.ally&&this.seen(e)&&dist(e,this.p)<=5)){this.hurtEnemy(e,this.has('scream')?28:15);if(this.has('devour'))this.heal(5);}this.p.echo+=this.equipment('armor')?.echo?2:4;}
  this.log(D.classes.find(x=>x.id===c).ability+' activated.','good');this.tick();
 }
 dash(dx,dy){if(this.s.ending)return;if(this.p.status.fracture>0){this.log('A fracture prevents dashing. Use a trauma kit or rest at a shelter.','bad');this.changed();return;}if(this.p.energy<5)return;const steps=this.has('tendon')?3:2;for(let n=0;n<steps;n++){let x=this.p.x+dx,y=this.p.y+dy;if(!this.walk(x,y)||this.enemyAt(x,y)||this.map.entities.some(e=>e.type==='npc'&&e.x===x&&e.y===y)||(dx&&dy&&(!this.walk(this.p.x+dx,this.p.y)||!this.walk(this.p.x,this.p.y+dy))))break;this.p.x=x;this.p.y=y;}this.p.energy-=5;this.tick();}
 toggleSneak(){this.p.sneak=!this.p.sneak;this.log(this.p.sneak?'You lower your profile. Detection range reduced.':'You stand upright.');this.changed();}
 learn(id){let t=D.talents.find(t=>t.id===id);if(!t||t.cls!==this.p.cls||this.p.points<1||this.has(id)||this.p.level<t.tier||this.p.specialization&&this.p.specialization!==t.path)return false;let previous=D.talents.find(x=>x.path===t.path&&x.cls===t.cls&&x.tier===t.tier-1);if(previous&&!this.has(previous.id))return false;this.p.specialization=t.path;this.p.talents.push(id);this.p.points--;if(id==='veteran'){this.p.maxHp+=25;this.heal(25);}if(id==='friends')for(const f of D.factions)this.s.rep[f.id]+=15;this.log(`You become a ${t.path}: ${t.name}.`,'story');this.vision();this.changed();return true;}
 train(stat){if(this.p.points<1)return;this.p.points--;this.p.stats[stat]++;if(stat===2){this.p.maxHp+=5;this.heal(5);}this.changed();}
 use(uid,target){let i=this.p.inventory.find(i=>i.uid===uid);if(!i||this.s.ending)return;let d=D.items[i.id];if(['weapon','armor','gear'].includes(d.type)){this.p[d.type]=uid;this.log('Equipped '+d.name+'.');this.tick();return;}
  if(d.type==='mod'){let w=this.equipped('weapon');if(!w||w.mods.length>=2||w.mods.includes(i.id)){this.log('Equip a weapon with a free modification slot (maximum 2).','hint');this.changed();return;}w.mods.push(i.id);this.take(i.id);this.log('Attached '+d.name+'.','good');this.tick();return;}
  if(d.type==='chrome'||d.type==='flesh'){this.log('Visit a district contact to install this augmentation.','hint');this.changed();return;}
  if(d.type!=='consumable')return;
  if(i.id==='grenade'){if(!target||!this.seen(target)||dist(this.p,target)>7){this.log('Select a visible enemy within 7 tiles first.','hint');this.changed();return;}for(const e of this.living())if(dist(e,target)<=2&&(!e.ally||!this.has('blast')))this.hurtEnemy(e,this.has('blast')?42:26);if(dist(this.p,target)<=2&&!this.has('blast'))this.damage(18,'your own grenade');}
  const boost=this.has('field')?2:1;
  if(i.id==='food')this.p.food=Math.min(100,this.p.food+38);if(i.id==='water'){this.p.water=Math.min(100,this.p.water+42);if(this.has('gills'))this.p.food=Math.min(100,this.p.food+15);}
  if(i.id==='medkit'){this.heal((32+(this.equipment('armor')?.heal?6:0))*boost);this.p.status={};}if(i.id==='bandage'){this.heal((10+(this.equipment('armor')?.heal?4:0))*boost);this.p.status.bleeding=0;}if(i.id==='antidote'){this.p.status.poison=0;this.p.status.infection=0;}if(i.id==='stim'){this.p.energy=Math.min(this.p.maxEnergy,this.p.energy+30);this.p.fatigue=Math.max(0,this.p.fatigue-20);this.p.food=Math.max(0,this.p.food-8);}if(i.id==='smoke')this.p.status.hidden=8;if(i.id==='battery')this.p.energy=Math.min(this.p.maxEnergy,this.p.energy+40);if(i.id==='repair'){let w=this.equipped('weapon');if(!w)return;w.durability=100;}this.take(i.id);this.log('Used '+d.name+'.','good');this.tick();
 }
 drop(uid,salvage=false){let i=this.p.inventory.find(i=>i.uid===uid);if(!i)return;const d=D.items[i.id];if(salvage&&!['weapon','armor','gear','valuable'].includes(d.type))return;this.p.inventory=this.p.inventory.filter(x=>x!==i);for(const slot of ['weapon','armor','gear'])if(this.p[slot]===uid)this.p[slot]=null;if(salvage){this.add('scrap',Math.max(1,Math.round(d.value/20)));if(this.has('recycler'))this.add('circuit');}else this.map.entities.push({uid:this.s.nextId++,type:'drop',x:this.p.x,y:this.p.y,item:i,name:d.name});this.log((salvage?'Salvaged ':'Dropped ')+d.name+'.');this.tick();}
 craft(id){let r=D.recipes.find(r=>r.id===id);if(!r)return;const cost=this.recipeCost(r);if(Object.entries(cost).some(([id,n])=>this.count(id)<n)){this.log('Missing crafting materials.','bad');this.changed();return;}for(const [id,n]of Object.entries(cost))this.take(id,n);this.add(id,r.n);this.log(`Crafted ${r.n} × ${D.items[id].name}.`,'good');this.tick(2);}
 recipeCost(r){return Object.fromEntries(Object.entries(r.cost).map(([id,n])=>[id,Math.max(1,Math.ceil(n*((this.p.cls==='engineer'||this.nearby('bench').length)?0.75:1)*(this.has('powder')&&['ammo','grenade'].includes(r.id)?0.5:1)))]));}
 interact(e){if(this.s.ending)return;const candidates=this.map.entities.filter(e=>dist(e,this.p)<=1&&e.type!=='enemy'&&e.type!=='sentry'&&!(e.type==='cache'&&e.opened)&&!(e.type==='event'&&e.done));if(!e){if(!candidates.length){this.log('Nothing within reach. Look for a person, locker, cot, terminal or route.','hint');this.changed();return;}if(candidates.length>1){this.prompt={title:'Within reach',text:'Choose something to interact with.',options:candidates.map(e=>({id:'entity:'+e.uid,label:e.name}))};this.changed();return;}e=candidates[0];}if(dist(e,this.p)>1)return;this.focus=e;
  if(e.type==='npc'){const f=D.factions.find(f=>f.id===e.faction);this.s.quests['main'+this.s.zone]??={state:'active',zone:this.s.zone};this.prompt={title:e.name,text:D.zones[this.s.zone].voice+' '+(this.s.rep[f.id]<-20?'Your name is unwelcome here. Services are closed.':this.s.quests['main'+this.s.zone]?.state==='done'?'People have heard what you did.':'Work: '+D.zones[this.s.zone].objective+'. Find the marked objective deep in this district.'),options:[{id:'shop',label:'Trade supplies',disabled:this.s.rep[f.id]<-20},{id:'clinic',label:'Treatment · 25 credits',disabled:this.s.rep[f.id]<-20},{id:'augment',label:'Chrome / Flesh installation',disabled:this.s.rep[f.id]<-20},{id:'job',label:'Ask about local work'},{id:'rumor',label:'Ask about escape routes'},{id:'pledge',label:'Pledge your future to '+f.name,disabled:this.s.rep[f.id]<45}]};}
  if(e.type==='bed'){this.prompt={title:'A light left on',text:'Shelter advances time without enemy turns. Eat and drink before a long rest. Your contact keeps watch. Beds require reputation above −20.',options:[{id:'rest2',label:'Rest 2 hours · recover 25 HP and energy',disabled:!this.safe()},{id:'rest8',label:'Sleep 8 hours · full recovery, clear injuries',disabled:!this.safe()}]};}
  if(e.type==='bench'){this.prompt={title:'Community workbench',text:'Repair your weapon here for 3 scrap. Crafting near this bench costs fewer materials.',options:[{id:'repairbench',label:'Repair equipped weapon · 3 scrap',disabled:!this.equipped('weapon')||(!this.has('rigging')&&this.count('scrap')<3)},{id:'craft',label:'Open crafting'}]};}
  if(e.type==='cache'){if(e.hidden&&!this.has('eyes')&&this.check('scout')<4){this.log('Something is concealed here, but you cannot locate the catch.');return;}if(e.locked){this.prompt={title:e.name,text:'A sealed locker. Force risks injury; a bypass consumes one circuit.',options:[{id:'hackcache',label:'Bypass · intellect 5 or neural jack',disabled:this.check('hack')<5||this.count('circuit')<1},{id:'forcecache',label:'Force the lock · 5 HP if strength < 5'},{id:'keycache',label:'Skeleton key',disabled:!this.has('skeleton')}]};}else this.loot(e);}
  if(e.type==='drop'){if(this.weight()+D.items[e.item.id].weight*e.item.qty>this.capacity()+10){this.log('Too heavy. Drop something first.','bad');return;}this.p.inventory.push(e.item);this.map.entities=this.map.entities.filter(x=>x!==e);this.log('Recovered '+e.name+'.');this.tick();}
  if(e.type==='gate')this.prompt={title:e.name,text:'Travel takes 1 hour. This city remembers what you leave behind. Enemies persist; supplies do not respawn.',options:[{id:'travel',label:'Enter '+D.zones[e.to].name}]};
  if(e.type==='duct')this.prompt={title:'Between the walls',text:'A narrow service route bypasses the main streets. Street Kids, Ghosts and agile survivors can use it.',options:[{id:'duct',label:'Take shortcut to '+D.zones[e.to].name,disabled:!(this.p.cls==='kid'||this.has('wayfinder')||this.check('stealth')>=6)}]};
  if(e.type==='objective'){if(e.done){this.log('You have already decided the fate of this place.');this.changed();return;}this.prompt={title:e.name,text:D.zones[this.s.zone].story+' The security seal has three possible weaknesses.',options:[{id:'objective-hack',label:'Hack the seal · intellect 5',disabled:this.check('hack')<5},{id:'objective-force',label:'Force entry · 10 HP, or no injury with strength 5 / Breach'},{id:'objective-social',label:'Call in a favor · presence 5 or local reputation 15',disabled:this.check('social')<5&&this.s.rep[D.zones[this.s.zone].faction]<15},{id:'objective-pay',label:'Buy an access code · 40 credits',disabled:this.p.credits<40}]};}
  if(e.type==='event')this.prompt={title:e.name,text:e.name.includes('terminal')?'The screen shows a photograph of you asleep. Its timestamp is tomorrow.':e.name.includes('family')?'They have barricaded the door from the outside. Someone must have promised to come back.':e.name.includes('shipment')?'Two faction stamps have been burned off the crate. You can still read them.':'The courier is bleeding onto a letter addressed to someone who no longer exists.',options:[{id:'event-help',label:e.name.includes('terminal')?'Listen · gain a fragment, +8 Echo':e.name.includes('shipment')?'Return shipment · local reputation +10':'Help · one medical supply, reputation +10',disabled:!e.name.includes('terminal')&&!e.name.includes('shipment')&&this.count('bandage')+this.count('medkit')===0&&this.p.cls!=='medic'},{id:'event-take',label:'Take what you can · supplies, reputation −8'},{id:'event-leave',label:'Leave it undisturbed'}]};
  if(e.type==='escape')this.escapePrompt(e.route);this.changed();
 }
 loot(e){e.opened=true;e.locked=false;let mult=(this.has('cache')?2:1);const found=[];for(let j=0;j<(this.p.cls==='kid'?3:2);j++){let id=this.pick(e.pool),n=(id==='ammo'?this.int(5,12):['scrap','cloth'].includes(id)?this.int(2,4):1)*mult;this.add(id,n);found.push(n+' '+D.items[id].name);}if(this.rand()<0.18){let pool=[['pipe','machete','coat','pack'],['jewelry','mesh','silencer'],['crossbow','rifle','scope'],['shotgun','flamer','plate','hammer'],['claws','organic','hazmat','tendon'],['katana','smg','railgun','reflex'],['lung','storage','gills','edge'],['eyes','dermal','jack','heart']][this.s.zone];let id=this.pick(pool);this.add(id);found.push(D.items[id].name);}if(this.night&&this.rand()<0.4){let id=this.pick(['data','circuit','battery','jewelry']);this.add(id);found.push(D.items[id].name);}this.s.scavenged++;this.gainXp(10);this.log('Scavenged: '+found.join(', ')+'.','good');if(this.weight()>this.capacity())this.log('Over capacity: fatigue accumulates faster. Drop or salvage unwanted equipment.','bad');this.prompt=null;this.tick();}
 choose(id){const e=this.focus;this.prompt=null;if(id.startsWith('entity:')){this.interact(this.map.entities.find(e=>e.uid===+id.split(':')[1]));return;}
  if(id==='shop'){this.prompt={title:e.name+' · Exchange',text:'Stock is finite and persists. Reputation and presence affect prices.',kind:'shop',faction:e.faction,options:[]};this.shopStock();}
  if(id==='clinic'){if(this.p.credits>=25){this.p.credits-=25;this.heal(this.p.maxHp);this.p.status={};this.p.echo=Math.max(0,this.p.echo-15);this.log('Your wounds close. The doctor does not ask where they came from.','good');this.tick(6,true);}else this.log('You need 25 credits.','bad');}
  if(id==='augment')this.prompt={title:'Chrome / Flesh clinic',kind:'augments',text:'Installation costs 30 credits per augmentation. Above 7 total strain, energy drains; an empty battery then causes rejection damage. Mixed modifications add 2 Echo each installation.',options:[]};
  if(id==='rumor'){this.log('Brin can run a train with the ignition core and turbine. Sable needs a manifest, 160 credits and Directorate trust. The Spire opens only at night, with three fragments and the unbroken frequency.','story');this.s.flags.routesKnown=true;this.prompt={title:'Three ways out',text:'TRAIN — complete Rainline and Cinderworks, bring 8 scrap; Union reputation 15 or intellect 6. AIR — complete Glass Meridian; 160 credits and Directorate reputation 15. ECHO — complete the Spire; 3 fragments, at night. District objectives always award one fragment. A fourth future is possible: earn 45 reputation and pledge yourself to a faction.',options:[]};}
  if(id==='job')this.localJob();
  if(id==='pledge'&&this.s.rep[e.faction]>=45){this.prompt={title:'Stay, and become part of it',text:'This ends your run. '+D.factions.find(f=>f.id===e.faction).goal+' They offer you a place, not a way out.',options:[{id:'end-faction',label:'Accept a life in the city'}]};}
  if(id==='end-faction')this.finish('faction',e.faction);
  if(id==='rest2'||id==='rest8'){if(this.safe()){const long=id==='rest8';this.tick(long?96:24,true);this.heal(long?this.p.maxHp:25);this.p.energy=this.p.maxEnergy;this.p.fatigue=Math.max(0,this.p.fatigue-(long?90:30));if(long)this.p.status={};this.log('You wake to '+(this.night?'a city of dark windows.':'gray light between the towers.'),'story');}}
  if(id==='repairbench'){if(this.equipped('weapon')&&(this.has('rigging')||this.take('scrap',3))){this.equipped('weapon').durability=100;this.tick(3);}}
  if(id==='craft')this.prompt={kind:'craft',title:'Workbench',text:'Make what will get you home.',options:[]};
  if(['hackcache','forcecache','keycache'].includes(id)){if(id==='hackcache'&&!this.take('circuit'))return;if(id==='forcecache'&&this.check('force')<5)this.damage(5,'forcing a locker','bleeding');this.loot(e);}
  if(id==='travel'||id==='duct')this.travel(e.to,id==='duct');
  if(id.startsWith('objective-')){if(id==='objective-pay'&&this.p.credits<40)return;if(id==='objective-pay')this.p.credits-=40;if(id==='objective-force'&&this.check('force')<5&&!this.has('breach'))this.damage(10,'forcing the security seal','fracture');if(!this.s.ending)this.prompt={title:'Who gets the future?',text:'You have secured '+e.name+'. Deliver it to the district’s people, or sell its leverage to their rival. You retain the knowledge needed for escape either way.',options:[{id:'objective-local',label:'Support '+D.factions.find(f=>f.id===D.zones[this.s.zone].faction).name+' · +20 reputation, 55 credits'},{id:'objective-rival',label:'Sell to their rival · +15 rival reputation, 100 credits'}]};}
  if(id==='objective-local'||id==='objective-rival'){const z=this.s.zone,f=D.zones[z].faction,r=D.factions.find(x=>x.id===f).enemy;e.done=true;this.s.quests['main'+z]={state:'done',zone:z};this.s.flags['objective'+z]=true;this.p.fragments+=this.has('listen')?2:1;if(id==='objective-local'){this.s.rep[f]+=20;this.s.rep[r]-=10;this.p.credits+=55;}else{this.s.rep[r]+=15;this.s.rep[f]-=20;this.p.credits+=100;}if(z===4&&this.has('mercy'))for(const f of D.factions)this.s.rep[f.id]+=15;this.gainXp(100+z*20);this.log(D.zones[z].objective+' — '+(id==='objective-local'?'the neighborhood will remember.':'someone else pays the cost.'),'story');this.tick();}
  if(id.startsWith('event-')){e.done=true;const f=D.zones[this.s.zone].faction;if(id==='event-help'){if(e.name.includes('terminal')){this.p.fragments++;this.p.echo+=8;this.log('The recording ends a second before you expected. You remember the missing second.','story');}else{if(!e.name.includes('shipment')&&this.p.cls!=='medic'){if(!this.take('bandage'))this.take('medkit');}this.s.rep[f]+=10;this.gainXp(35);this.log('Someone will remember that you stopped.','story');}}if(id==='event-take'){this.add('food',2);this.add('ammo',8);this.p.credits+=20;this.s.rep[f]-=8;this.log('You leave with heavier pockets.','story');}this.tick();}
  if(id==='end-train'||id==='end-air'||id==='end-echo')this.finish(id.slice(4),'escape');
  if(id==='local-complete')this.completeLocal();this.changed();
 }
 localJob(){const z=this.s.zone,key='local'+z;let q=this.s.quests[key];if(!q)q=this.s.quests[key]={state:'active',zone:z,startKills:this.s.kills,startScavenged:this.s.scavenged};const names=['Three clean waters','Dressings for the ward','Clear the route','Salvage for the furnaces','Emergency medicine','An archive with holes','Power for the pumps','Something worth remembering'];const requirements=['Bring 3 clean water.','Bring 4 pressure dressings.','Defeat 5 enemies after accepting this job.','Bring 10 mechanical scrap.','Bring 2 trauma kits.','Bring 3 encrypted data.','Bring 3 intact circuits.','Gather at least 5 Echo fragments.'];this.prompt={title:names[z],text:q.state==='done'?'Your work here is finished.':requirements[z]+' Reward: 60 credits, 60 XP and +12 local reputation.',options:q.state==='done'?[]:[{id:'local-complete',label:'Complete the job',disabled:!this.localReady(z)}]};}
 localReady(z){let q=this.s.quests['local'+z];if(!q||q.state==='done')return false;return [()=>this.count('water')>=3,()=>this.count('bandage')>=4,()=>this.s.kills-q.startKills>=5,()=>this.count('scrap')>=10,()=>this.count('medkit')>=2,()=>this.count('data')>=3,()=>this.count('circuit')>=3,()=>this.p.fragments>=5][z]();}
 completeLocal(){let z=this.s.zone;if(!this.localReady(z))return;const costs=[['water',3],['bandage',4],null,['scrap',10],['medkit',2],['data',3],['circuit',3],null];if(costs[z])this.take(...costs[z]);this.s.quests['local'+z].state='done';this.p.credits+=60;this.s.rep[D.zones[z].faction]+=12;this.gainXp(60);this.log('Local work completed. You have become useful to this neighborhood.','story');}
 shopStock(){if(this.map.stock)return this.map.stock;let f=D.zones[this.s.zone].faction;const specials={union:['rifle','shotgun','vest','rig','muscle','dermal'],garden:['medkit','antidote','blood','gills','heart','skin','tendon'],crown:['smg','railgun','mesh','scope','reflex','eyes','silencer'],choir:['rod','battery','jack','lung','storage','shroud','edge']};this.map.stock=Object.fromEntries(['food','water','bandage','ammo','scrap','circuit','repair',...specials[f]].map(id=>[id,id==='ammo'?60:['food','water','scrap'].includes(id)?12:3]));return this.map.stock;}
 price(id,sell=false){const rep=this.s.rep[D.zones[this.s.zone].faction];return Math.max(1,Math.round(D.items[id].value*(sell?0.45:Math.max(0.45,1.2-rep/150-this.p.stats[5]*0.02-(this.has('broker')?0.3:0)))));}
 buy(id,n=1){const stock=this.shopStock(),price=this.price(id)*n;if(stock[id]<n||this.p.credits<price)return false;stock[id]-=n;this.p.credits-=price;this.add(id,n);this.log('Purchased '+n+' × '+D.items[id].name+'.');this.changed();return true;}
 sell(uid){let i=this.p.inventory.find(i=>i.uid===uid);if(!i)return;this.p.credits+=this.price(i.id,true);this.shopStock()[i.id]=(this.shopStock()[i.id]||0)+1;i.qty--;if(!i.qty){this.p.inventory=this.p.inventory.filter(x=>x!==i);for(const s of ['weapon','armor','gear'])if(this.p[s]===uid)this.p[s]=null;}this.changed();}
 install(id){const d=D.items[id];if(!d||!['chrome','flesh'].includes(d.type)||this.has(id)||this.count(id)<1||this.p.credits<30)return false;this.take(id);this.p.credits-=30;this.p.augments.push(id);if(this.p.augments.some(a=>D.items[a].type!==d.type))this.p.echo+=2;if(d.type==='chrome'){this.s.rep.choir+=2;this.s.rep.garden-=2;}else{this.s.rep.garden+=2;this.s.rep.choir-=2;}this.log('Installed '+d.name+'. Your reflection is a little less familiar.','story');this.tick(6,true);return true;}
 removeAugment(id){if(this.p.credits<20||!this.has(id))return;this.p.credits-=20;this.p.augments=this.p.augments.filter(x=>x!==id);this.add(id);this.tick(6,true);}
 travel(to,shortcut=false){if(this.s.ending)return;this.s.time+=shortcut?30:60;this.p.food=Math.max(0,this.p.food-3);this.p.water=Math.max(0,this.p.water-4);this.p.fatigue=Math.min(100,this.p.fatigue+3);this.s.zone=to;this.s.maps[to]??=this.generate(to);this.p.x=this.map.start.x;this.p.y=this.map.start.y;if(!this.s.visited.includes(to)){this.s.visited.push(to);this.gainXp(40);this.log('First arrival: '+D.zones[to].name+'. '+D.zones[to].sub+'.','story');}else this.log('You return to '+D.zones[to].name+'.');this.prompt=null;this.vision();this.changed();}
 escapeReady(route){if(route==='train')return !!(this.s.flags.objective2&&this.s.flags.objective3&&this.count('scrap')>=8&&(this.s.rep.union>=15||this.check('hack')>=6));if(route==='air')return !!(this.s.flags.objective5&&this.p.credits>=160&&this.s.rep.crown>=15);return !!(this.s.flags.objective7&&this.p.fragments>=3&&this.night);}
 escapePrompt(route){const text={train:'Restore the evacuation train. Requires the Rainline ignition core, Cinderworks turbine, 8 scrap, and Union reputation 15 or intellect 6. Families will travel with you.',air:'Purchase a seat out. Requires the Glass Meridian manifest, 160 credits, and Directorate reputation 15. The helicopter has room for only you.',echo:'Tune the impossible door. Requires the Spire frequency, 3 Echo fragments, and night. No one can tell you what leaving means here.'};this.prompt={title:{train:'The last train',air:'Above the fracture',echo:'Between stations'}[route],text:text[route],options:[{id:'end-'+route,label:'Commit to this ending',disabled:!this.escapeReady(route)}]};}
 worldEvent(){const type=this.int(0,5);if(type===0){this.s.weather=this.pick(['Acid rain','Dry lightning','Low fog','Rain','Clear']);this.log('The weather turns: '+this.s.weather+'.','story');}if(type===1){this.map.blackout=this.s.turn+12;this.log('A rolling blackout swallows the district. Visibility drops for an hour.','story');}if(type===2){this.p.echo+=3;this.log('A public address system repeats your last footsteps. Then it takes one more.','story');}if(type===3){this.add('scrap',2);this.log('A maintenance drone drops a broken panel at your feet. Salvaged 2 scrap.','good');}if(type===4){let e=this.living().find(e=>!e.boss&&!e.ally);if(e){e.hp=Math.max(1,e.hp-10);this.log('Gunfire somewhere beyond the walls. A territorial clash leaves a patrol wounded.','story');}}if(type===5&&this.night){const p=this.map.rooms[8];let key=this.pick(['wraith','hound']),b=D.enemies[key];if(!this.living().some(e=>e.x===p.cx&&e.y===p.cy))this.map.entities.push({uid:this.s.nextId++,type:'enemy',...b,key,x:p.cx,y:p.cy,maxHp:b.hp,status:{},alert:0});this.log('Night brings something new into the district.','story');}}
 finish(type,cause){if(this.s.ending)return;const texts={death:`${this.p.name} did not leave the city. ${cause} ended the run. Somewhere, a lamp remains lit for someone who will not return.`,train:'The train lurches out of the rain. Behind you, families count each other in the dark. In the final window of the city, a light moves against the direction of travel.',air:'From above, the fracture looks almost deliberate. Sable hands you a blank identity. The pilot asks if you have been here before. You answer too quickly.',echo:'You step between two stations. The city on the other side is whole. A familiar stranger opens a door and says your name. The radio in your pocket begins to ring.',faction:'You stop looking for a way out. Someone has to keep the lights on. Over the following years, strangers learn your name as a place of safety—or a warning.'};this.s.ending={type,cause,text:texts[type],day:this.day,turns:this.s.turn};this.log(texts[type],'story');this.prompt=null;this.changed();}
 serialize(){return JSON.stringify(this.s);}
 static load(text){const s=JSON.parse(text),fail=()=>{throw Error('This is not a compatible Night Run save.');};if(!s||s.version!==1||!s.p||!s.maps||!D.classes.some(c=>c.id===s.p.cls)||!s.maps[s.zone]||!Array.isArray(s.p.inventory))fail();
  const p=s.p,finite=n=>typeof n==='number'&&Number.isFinite(n);if(!['turn','time','rng','nextId','zone','kills','scavenged'].every(k=>finite(s[k]))||!['x','y','hp','maxHp','energy','maxEnergy','food','water','fatigue','xp','level','points','credits','echo','fragments','cooldown'].every(k=>finite(p[k]))||!Array.isArray(p.stats)||p.stats.length!==6||!p.stats.every(finite)||!p.status||!s.flags||!s.rep||!s.quests||!Array.isArray(s.visited)||!Array.isArray(s.log)||!Array.isArray(s.history))fail();
  if(!Array.isArray(p.augments)||p.augments.some(id=>!D.items[id]||!['chrome','flesh'].includes(D.items[id].type))||!Array.isArray(p.talents)||p.talents.some(id=>!D.talents.some(t=>t.id===id))||p.specialization&&!D.classes.find(c=>c.id===p.cls).paths.includes(p.specialization))fail();
  for(const i of p.inventory)if(!D.items[i.id]||!finite(i.uid)||!finite(i.qty)||i.qty<=0||!Array.isArray(i.mods)||i.mods.some(id=>!['scope','silencer','edge'].includes(id)))fail();
  for(const [z,m]of Object.entries(s.maps)){if(!D.zones[z]||m.w!==44||m.h!==32||!Array.isArray(m.tiles)||m.tiles.length!==m.w*m.h||!Array.isArray(m.seen)||m.seen.length!==m.tiles.length||!Array.isArray(m.entities)||!Array.isArray(m.rooms)||!m.start)fail();for(const e of m.entities)if(!['enemy','npc','cache','bed','bench','gate','objective','event','duct','escape','sentry','drop'].includes(e.type)||!Number.isInteger(e.x)||!Number.isInteger(e.y)||e.x<0||e.y<0||e.x>=m.w||e.y>=m.h)fail();if(m.stock&&Object.keys(m.stock).some(id=>!D.items[id]))fail();}
  if(p.x<0||p.y<0||p.x>=44||p.y>=32||D.factions.some(f=>!finite(s.rep[f.id])))fail();for(const l of s.log)if(!['normal','hint','story','bad','good','combat'].includes(l.type))fail();for(const q of Object.values(s.quests))if(!['active','done'].includes(q.state))fail();return new Game(s);}
}
root.NRGame=Game;root.NRDist=dist;if(typeof module!=='undefined')module.exports=Game;
})(typeof window!=='undefined'?window:globalThis);
