(function(){
'use strict';
const D=NRData,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SAVE='fractured-city-night-run-v1',META='fractured-city-night-run-memories',SETTINGS='fractured-city-night-run-settings';
let g=null,view='',filter='all',selectedClass='kid',target=null,tileSize=30,cam={x:0,y:0},anim=[],autoWalk=null,createName='Ash',createSeed='',audioCtx=null,savedAvailable=false,dashMode=false;
let settings={sound:true,motion:true,contrast:false},memories=[];try{Object.assign(settings,JSON.parse(localStorage.getItem(SETTINGS)||'{}'));memories=JSON.parse(localStorage.getItem(META)||'[]');savedAvailable=!!localStorage.getItem(SAVE);}catch{}
function applySettings(){document.body.classList.toggle('high-contrast',settings.contrast);document.body.classList.toggle('reduced-motion',!settings.motion);try{localStorage.setItem(SETTINGS,JSON.stringify(settings));}catch{}}
applySettings();$('continueButton').disabled=!savedAvailable;if(memories.length)$('legacy').textContent=`${memories.length} ${memories.length===1?'life':'lives'} remembered. Last echo: ${memories.at(-1).name}, ${memories.at(-1).ending}.`;
function sound(type='click'){if(!settings.sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();let o=audioCtx.createOscillator(),a=audioCtx.createGain();o.connect(a);a.connect(audioCtx.destination);o.type=type==='hurt'?'sawtooth':'sine';o.frequency.setValueAtTime(type==='hurt'?80:type==='attack'?180:440,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(type==='click'?330:35,audioCtx.currentTime+.1);a.gain.setValueAtTime(.025,audioCtx.currentTime);a.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.12);o.start();o.stop(audioCtx.currentTime+.13);}catch{}}
function open(title,body,kicker='FIELD TERMINAL'){stopWalk();$('modalTitle').textContent=title;$('modalKicker').textContent=kicker;$('modalBody').innerHTML=body;$('modal').hidden=false;}
function close(){if(g?.s.ending&&view==='ending')return;$('modal').hidden=true;view='';if(g)g.prompt=null;$('mapCanvas').focus({preventScroll:true});}
function attach(game){g=game;window.nightRun=g;target=null;dashMode=false;document.body.classList.add('playing');g.onchange=update;$('titleScreen').hidden=true;$('gameScreen').hidden=false;$('modal').hidden=true;view='';update();}
function update(){if(!g)return;renderHUD();draw();const effects=g.effects.splice(0);for(const e of effects){anim.push({...e,start:performance.now()});sound(e.type);}if(g.s.ending){try{localStorage.removeItem(SAVE);}catch{}if(!g.s.flags.recorded){g.s.flags.recorded=true;memories.push({name:g.p.name,ending:g.s.ending.type,seed:g.s.seed,day:g.day});try{localStorage.setItem(META,JSON.stringify(memories));}catch{}}ending();return;}try{localStorage.setItem(SAVE,g.serialize());$('saveState').textContent='● SAVED LOCALLY';}catch{$('saveState').textContent='EXPORT SAVE TO KEEP PROGRESS';}if(g.prompt)renderPrompt();else if(view==='inventory')inventory();else if(view==='talents')talents();else if(view==='craft')crafting();else if(view==='shop')shop();else if(view==='augments')augments();}
function renderHUD(){const p=g.p,z=D.zones[g.s.zone],c=D.classes.find(c=>c.id===p.cls),hours=Math.floor(g.s.time/60)%24,mins=g.s.time%60;document.documentElement.style.setProperty('--accent',z.color);
 $('worldClock').innerHTML=`<b>${g.night?'☾':'☀'} DAY ${g.day}</b><span>${String(hours).padStart(2,'0')}:${String(mins).padStart(2,'0')}</span><span>${esc(g.s.weather)}</span>`;
 $('districtType').textContent=`DISTRICT 0${g.s.zone+1} / ${z.kind.toUpperCase()}`;$('districtName').textContent=z.name;$('districtDanger').innerHTML=`THREAT ${'▰'.repeat(z.danger)}${'▱'.repeat(5-z.danger)}<br>${g.night?'NIGHT SALVAGE ACTIVE':'DAYLIGHT HOURS'}`;$('mapSubtitle').textContent=(g.map.rooms.find(r=>p.x>=r.x&&p.x<r.x+r.w&&p.y>=r.y&&p.y<r.y+r.h)?.name||'Service passage').toUpperCase()+' / '+(g.night?'AFTER DARK':'DAYLIGHT');
 $('mobileVitals').innerHTML=`<span style="color:var(--red)">HP ${Math.ceil(p.hp)}/${p.maxHp}</span><span>EN ${Math.floor(p.energy)}</span><span>FOOD ${Math.ceil(p.food)}%</span><span>WATER ${Math.ceil(p.water)}%</span><button data-act="inventory">Pack</button><button data-act="talents">LV ${p.level}${p.points?' +':''}</button>`;
 $('character').innerHTML=`<div class="portrait">${{kid:'◈',soldier:'⛨',hacker:'⌘',medic:'✚',engineer:'⚒',sensitive:'◉'}[p.cls]}</div><h3>${esc(p.name)}</h3><div class="class-line">${c.name.toUpperCase()}<br>${p.specialization||'UNSPECIALIZED'}</div><div class="level-line"><span>LEVEL ${p.level}</span><span>${p.points} TALENT ${p.points===1?'POINT':'POINTS'}</span></div><div class="xp-bar"><i style="width:${p.xp/(p.level*65)*100}%"></i></div>`;
 const meter=(name,val,max,color)=>`<div class="meter"><div class="meter-label"><span>${name}</span><span>${Math.ceil(val)} / ${max}</span></div><div class="meter-track"><i style="width:${Math.max(0,val/max*100)}%;background:${color}"></i></div></div>`;
 $('vitals').innerHTML=meter('VITALITY',p.hp,p.maxHp,'#cf9581')+meter('ENERGY',p.energy,p.maxEnergy,'#86bcb0')+`<div class="minor-vitals"><div><span>NUTRITION</span><b style="color:${p.food<20?'var(--red)':'inherit'}">${Math.ceil(p.food)}%</b></div><div><span>HYDRATION</span><b style="color:${p.water<20?'var(--red)':'inherit'}">${Math.ceil(p.water)}%</b></div><div><span>FATIGUE</span><b>${Math.floor(p.fatigue)}%</b></div><div><span>CREDITS</span><b style="color:var(--amber)">${p.credits} ¢</b></div></div>`;
 const w=g.equipment('weapon'),a=g.equipment('armor');$('loadout').innerHTML=`<div class="section-label">EQUIPPED</div><div class="equipment-row"><small>WEAPON</small><b>${w?.name||'Bare hands'}</b><em>${w?w.damage+' DMG · '+w.range+' RANGE · '+Math.floor(w.durability)+'% CONDITION':'2 DMG · 1 RANGE'}</em></div><div class="equipment-row"><small>ARMOR</small><b>${a?.name||'None'}</b><em>${g.armor()} PROTECTION</em></div><div class="equipment-row"><small>PACK</small><b>${g.weight().toFixed(1)} / ${g.capacity()} kg</b><em>${g.count('ammo')} CARTRIDGES</em></div>`;
 $('conditions').innerHTML=Object.entries(p.status).filter(([k,v])=>v>0).map(([k,v])=>`<span class="status-pill ${['hidden','overwatch'].includes(k)?'good':''}" title="${v} turns remaining">${k.toUpperCase()} ${v}</span>`).join('');
 $('abilityButton').innerHTML=`<kbd>1</kbd> ${c.ability}${p.cooldown?' · '+p.cooldown:''}`;$('abilityButton').title=c.effect;$('sneakButton').classList.toggle('active',p.sneak);
 const entities=g.map.entities.filter(e=>g.seen(e)&&!(e.type==='enemy'&&e.hp<=0)&&!(e.hidden&&!g.has('eyes')&&g.check('scout')<4)).sort((a,b)=>NRDist(g.p,a)-NRDist(g.p,b));
 $('nearby').innerHTML=`<div class="section-label">IN YOUR SIGHT <span>${entities.filter(e=>e.type==='enemy').length} CONTACTS</span></div>`+entities.slice(0,5).map(e=>`<div class="nearby-item"><span class="symbol" style="color:${e.color||z.color}">${glyph(e)}</span><button data-entity="${e.uid}">${esc(e.name)}<small>${e.type==='enemy'?`${Math.max(0,e.hp)} HP · ${e.ally?'ALLY':e.alert?'ALERT':'UNAWARE'}`:e.type==='cache'?e.opened?'EMPTY':'SCAVENGE':e.type.toUpperCase()} · ${NRDist(g.p,e)} m</small></button></div>`).join('');
 const done=g.s.flags['objective'+g.s.zone];$('currentQuest').innerHTML=`<div class="quest-card"><div class="tag">${done?'✓ COMPLETED':'DISTRICT THREAD'}</div><h4>${z.objective}</h4><p>${done?'Your decision has become part of this neighborhood.':'Speak to '+z.npc+'. The objective lies deep inside the district.'}</p><button data-act="journal">Open journal →</button></div>`;
 $('echoPanel').innerHTML=`<p>“${p.echo<15?'If you can hear this, leave a light on.':p.echo<40?'We have a recording of tomorrow. You are in it.':'You keep calling it escape. We keep calling it coming home.'}”</p><div class="echo-number">${p.fragments} FRAGMENTS · ${Math.floor(p.echo)} EXPOSURE</div>`;
 $('factions').innerHTML=D.factions.map(f=>`<div class="faction-row"><span style="color:${f.color}">${f.name}</span><b>${g.s.rep[f.id]>0?'+':''}${g.s.rep[f.id]}</b></div>`).join('');$('turnNumber').textContent=`TURN ${g.s.turn} · SEED ${g.s.seed}`;
 $('eventLog').innerHTML=g.s.log.slice(-35).map(l=>`<div class="log-entry ${l.type}"><span>${String(l.turn).padStart(3,'0')}</span>${esc(l.text)}</div>`).join('');$('eventLog').scrollTop=$('eventLog').scrollHeight;
}
function glyph(e){return({npc:'♙',cache:e.opened?'▫':'▣',bed:'⌂',bench:'⚒',gate:'↗',objective:e.done?'✓':'◈',event:'?',duct:'⇄',escape:'◎',sentry:'†',drop:'◇'})[e.type]||e.glyph||'?';}
function draw(){if(!g)return;const canvas=$('mapCanvas'),ctx=canvas.getContext('2d'),W=canvas.width=Math.max(320,Math.round(canvas.clientWidth)),H=canvas.height=Math.max(100,Math.round(canvas.clientHeight)),T=tileSize,m=g.map,z=D.zones[g.s.zone];ctx.fillStyle='#070d12';ctx.fillRect(0,0,W,H);cam.x=Math.max(0,Math.min(m.w-W/T,g.p.x-W/T/2));cam.y=Math.max(0,Math.min(m.h-H/T,g.p.y-H/T/2));if(m.w<W/T)cam.x=(m.w-W/T)/2;if(m.h<H/T)cam.y=(m.h-H/T)/2;
 const x0=Math.max(0,Math.floor(cam.x)),y0=Math.max(0,Math.floor(cam.y)),x1=Math.min(m.w,Math.ceil(cam.x+W/T)),y1=Math.min(m.h,Math.ceil(cam.y+H/T));
 for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){let i=y*m.w+x;if(!m.seen[i])continue;let vis=g.visible.has(i),px=Math.round((x-cam.x)*T),py=Math.round((y-cam.y)*T),t=m.tiles[i],hash=(x*113+y*53+g.s.zone*71)%19;
  ctx.globalAlpha=vis?1:.27;ctx.fillStyle=t==='#'?z.wall:z.floor;ctx.fillRect(px,py,T+1,T+1);
  if(t==='#'){ctx.fillStyle='#ffffff09';ctx.fillRect(px,py,T,3);ctx.fillStyle='#00000045';ctx.fillRect(px,py+T-4,T,4);ctx.strokeStyle='#060c1544';ctx.strokeRect(px+1,py+1,T-2,T-2);if(hash<4){ctx.fillStyle=z.color+'22';ctx.fillRect(px+5,py+8,T-10,3);}}
  else{ctx.fillStyle=hash<9?'#ffffff05':'#00000009';ctx.fillRect(px+1,py+1,T-2,T-2);ctx.fillStyle='#758b9612';if(hash<5)ctx.fillRect(px+hash+4,py+15,10,1);if(t==='='){ctx.fillStyle='#34424a';ctx.fillRect(px+4,py+7,T-8,T-12);ctx.fillStyle='#738081';ctx.fillRect(px+5,py+7,T-10,3);ctx.fillStyle='#10181e';ctx.fillRect(px+7,py+T-6,T-11,2);}if(t==='+'){ctx.fillStyle='#736653';ctx.fillRect(px+5,py+2,T-10,T-4);ctx.fillStyle='#c6ae72';ctx.fillRect(px+T-10,py+T/2,3,3);}if(t==='~'){ctx.fillStyle='#548f6544';ctx.fillRect(px,py,T,T);ctx.strokeStyle='#81b69e66';ctx.beginPath();ctx.moveTo(px+4,py+10);ctx.lineTo(px+T-5,py+12);ctx.moveTo(px+8,py+21);ctx.lineTo(px+T-3,py+19);ctx.stroke();}if(t==='!'){ctx.fillStyle='#a34c2844';ctx.fillRect(px,py,T,T);ctx.fillStyle='#d27b40';ctx.beginPath();ctx.moveTo(px+5,py+T-5);ctx.lineTo(px+T/2,py+5);ctx.lineTo(px+T-5,py+T-5);ctx.fill();}}
 }
 ctx.globalAlpha=1;
 for(const e of m.entities){if(!g.seen(e)||e.type==='enemy'&&e.hp<=0||e.type==='sentry'&&e.life<=0||e.hidden&&!g.has('eyes')&&g.check('scout')<4)continue;let px=(e.x-cam.x)*T,py=(e.y-cam.y)*T;ctx.save();if(e.type==='enemy'||e.type==='npc'){drawPerson(ctx,px,py,T,e.type==='npc'?z.color:e.ally?'#97d7a4':e.color,e.machine,e.type==='enemy'&&e.boss);if(e.type==='enemy'){ctx.fillStyle='#243039';ctx.fillRect(px+3,py-3,T-6,3);ctx.fillStyle=e.ally?'#9ed4a4':'#d68a7a';ctx.fillRect(px+3,py-3,(T-6)*Math.max(0,e.hp/e.maxHp),3);if(e.alert>0){ctx.fillStyle='#edb870';ctx.font='bold 10px monospace';ctx.fillText('!',px+T-4,py+8);}}}else{ctx.font=`${Math.floor(T*.65)}px Consolas, monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=e.type==='cache'?(e.opened?'#677574':'#c0ab78'):e.type==='escape'?'#d2b7ff':e.type==='objective'?'#cfb9e2':e.type==='gate'?'#9bccb4':z.color;ctx.fillText(glyph(e),px+T/2,py+T/2);if(e.type==='gate'){ctx.fillStyle='#6fa99235';ctx.fillRect(px,py,T,T);}}
  if(e.uid===target){ctx.strokeStyle='#e7bf7e';ctx.lineWidth=2;ctx.strokeRect(px-2,py-2,T+4,T+4);}ctx.restore();
 }
 let px=(g.p.x-cam.x)*T,py=(g.p.y-cam.y)*T;ctx.strokeStyle=g.p.sneak?'#b7a1da':'#a8e3c0';ctx.lineWidth=1;ctx.strokeRect(px-2,py-2,T+4,T+4);ctx.fillStyle='#91cfb31a';ctx.fillRect(px-T/2,py-T/2,T*2,T*2);drawPerson(ctx,px,py,T,g.p.sneak?'#b0a0d8':'#a4d7b7',false,false,true);
 if(settings.motion){for(const a of anim){let age=(performance.now()-a.start)/700;if(age>1)continue;ctx.globalAlpha=1-age;ctx.font='bold 18px Consolas,monospace';ctx.textAlign='center';ctx.fillStyle=a.type==='hurt'?'#ff8f86':'#fff0b7';ctx.fillText((a.type==='hurt'?'-':'')+a.value,(a.x-cam.x+.5)*T,(a.y-cam.y)*T-age*25);if(a.from&&age<.2){ctx.strokeStyle='#f4d788';ctx.beginPath();ctx.moveTo((a.from.x-cam.x+.5)*T,(a.from.y-cam.y+.5)*T);ctx.lineTo((a.x-cam.x+.5)*T,(a.y-cam.y+.5)*T);ctx.stroke();}}ctx.globalAlpha=1;}
 const mc=$('minimap').getContext('2d');mc.fillStyle='#0a1117';mc.fillRect(0,0,220,160);for(let y=0;y<m.h;y++)for(let x=0;x<m.w;x++){let i=y*m.w+x;if(!m.seen[i])continue;mc.fillStyle=m.tiles[i]==='#'?'#2a3d43':'#506a6a';mc.globalAlpha=g.visible.has(i)?1:.45;mc.fillRect(x*5,y*5,5,5);}mc.globalAlpha=1;for(const e of m.entities)if(m.seen[e.y*m.w+e.x]&&['npc','gate','objective','escape'].includes(e.type)){mc.fillStyle=e.type==='objective'?'#bf9fd6':e.type==='npc'?'#dfbb7b':'#8cbfa9';mc.fillRect(e.x*5,e.y*5,5,5);}mc.fillStyle='#edecd6';mc.fillRect(g.p.x*5,g.p.y*5,5,5);
}
function drawPerson(ctx,x,y,t,color,machine=false,boss=false,player=false){let s=t/30;ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(15,25,10,4,0,0,Math.PI*2);ctx.fill();if(machine){ctx.fillStyle='#24363f';ctx.fillRect(3,7,24,15);ctx.fillStyle=color;ctx.fillRect(7,10,16,8);ctx.fillStyle='#def8ff';ctx.fillRect(12,12,6,3);ctx.fillStyle='#839aa1';ctx.fillRect(1,10,4,8);ctx.fillRect(25,10,4,8);}else{ctx.fillStyle='#243239';ctx.fillRect(9,20,5,8);ctx.fillRect(17,20,5,8);ctx.fillStyle=color;ctx.fillRect(boss?4:7,11,boss?23:17,12);ctx.fillStyle='#1c2932';ctx.fillRect(11,12,7,11);ctx.fillStyle=color;ctx.fillRect(10,3,12,11);ctx.fillStyle=player?'#1c3434':'#28343a';ctx.fillRect(12,7,8,6);ctx.fillStyle=player?'#fff6cf':'#e0c8a4';ctx.fillRect(14,8,5,2);ctx.fillStyle='#859197';ctx.fillRect(23,12,3,11);if(player){ctx.fillStyle='#d9c08b';ctx.fillRect(7,12,3,10);}}ctx.restore();}
function frame(){if(anim.length){anim=anim.filter(a=>performance.now()-a.start<700);draw();}requestAnimationFrame(frame);}requestAnimationFrame(frame);
function creation(){view='create';const c=D.classes.find(c=>c.id===selectedClass);open('Who enters the city?',`<p class="modal-intro">Your past changes how you survive. Your choices decide who leaves.</p><div class="create-grid">${D.classes.map((c,i)=>`<button class="class-card ${selectedClass===c.id?'selected':''}" data-class="${c.id}"><div class="num">0${i+1} / ${c.paths.join(' · ').toUpperCase()}</div><h3>${c.name}</h3><p>${c.tag}</p></button>`).join('')}</div><div class="class-detail"><strong>${c.name}</strong><p>${c.desc}</p><p><b>${c.ability}:</b> ${c.effect}</p><p>Starting equipment: ${D.items[c.weapon].name}, ${D.items[c.armor].name}.</p></div><div class="inline-fields"><div><label for="runnerName">RUNNER NAME</label><input id="runnerName" maxlength="24" value="${esc(createName)}" placeholder="Ash"></div><div><label for="citySeed">CITY SEED · OPTIONAL</label><input id="citySeed" maxlength="40" value="${esc(createSeed)}" placeholder="A new city every time"></div></div><div class="notice" style="margin-top:20px">One active run. Death deletes its local save. Starting a new life replaces an existing run. Export a save first if you want an archive.</div><div class="footer-actions"><button data-act="close">Back</button><button class="primary" data-act="start">Begin the night run →</button></div>`,'CHARACTER CREATION');}
function describe(id,i){const d=D.items[id];return d.type==='weapon'?`${d.damage} damage · ${d.range+(i?.mods?.includes('scope')?2:0)} range${d.ammo?' · '+d.ammo+' ammo / shot':''}${d.pierce?' · pierces '+d.pierce+' armor':''} · ${Math.floor(i?.durability??100)}% condition${i?.mods?.length?' · '+i.mods.map(x=>D.items[x].name).join(', '):''}`:d.type==='armor'?`${d.armor} protection${d.stealth?' · stealth +'+d.stealth:''}${d.resist?' · hazard resistance '+d.resist:''}${d.regen?' · regenerates health':''}`:d.capacity?'Carry capacity +'+d.capacity+' kg':d.desc||({material:'Used in crafting and repairs.',ammo:'Compatible with all scavenged ranged weapons.',valuable:'Sell to a trader, or keep for local work.'})[d.type]||'';}
function inventory(){view='inventory';const types=['all','weapon','armor','consumable','material','chrome','flesh','valuable'];open('Everything you carry',`<div class="inventory-summary"><span>${g.weight().toFixed(1)} / ${g.capacity()} KG</span><span>${g.p.credits} CREDITS</span><span>${g.p.inventory.length} STACKS</span></div><div class="tabs">${types.map(t=>`<button class="${filter===t?'selected':''}" data-filter="${t}">${t==='all'?'All items':t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div><div class="item-grid">${g.p.inventory.filter(i=>filter==='all'||D.items[i.id].type===filter).map(i=>{let d=D.items[i.id],equipped=['weapon','armor','gear'].some(s=>g.p[s]===i.uid);return `<div class="item-card ${equipped?'highlight':''}"><div class="item-type">${d.type}${equipped?' · EQUIPPED':''} · ${(d.weight*i.qty).toFixed(1)} KG</div><h4>${d.name}${i.qty>1?' × '+i.qty:''}</h4><p>${describe(i.id,i)}</p><div class="buttons">${['weapon','armor','gear','consumable','mod'].includes(d.type)?`<button data-use="${i.uid}">${['weapon','armor','gear'].includes(d.type)?'Equip':d.type==='mod'?'Attach':'Use'}</button>`:''}<button data-drop="${i.uid}">Drop stack</button>${['weapon','armor','gear','valuable'].includes(d.type)?`<button data-salvage="${i.uid}">Salvage</button>`:''}</div></div>`;}).join('')||'<p class="empty">Nothing in this category.</p>'}</div>`,'PACK / EQUIPMENT');}
function talents(){view='talents';const c=D.classes.find(c=>c.id===g.p.cls);open('Become someone else',`<div class="inventory-summary"><span>LEVEL ${g.p.level}</span><span>${g.p.points} AVAILABLE POINTS</span><span>${g.p.specialization||'CHOOSE A PATH'}</span></div><p class="modal-intro">Choose one specialization for this life. Talents unlock at levels 1, 2 and 3, in order. Spend later points on attributes to refine your build.</p><div class="stats-grid">${['Strength','Agility','Endurance','Perception','Intellect','Presence'].map((n,i)=>`<div class="stat-card" title="${['Melee damage, force checks, carrying capacity','Evasion, stealth and service ducts','Maximum health','Vision and ranged damage','Hacking and train engineering','Dialogue checks and trade prices'][i]}"><span>${n}</span><strong>${g.p.stats[i]}</strong><button data-stat="${i}" ${g.p.points?'':'disabled'}>+</button></div>`).join('')}</div><div class="tree-columns">${c.paths.map(path=>`<div class="tree-column"><h3>${path}</h3>${D.talents.filter(t=>t.cls===c.id&&t.path===path).map(t=>{let learned=g.has(t.id),prev=D.talents.find(x=>x.cls===c.id&&x.path===path&&x.tier===t.tier-1),can=!learned&&g.p.points&&g.p.level>=t.tier&&(!g.p.specialization||g.p.specialization===path)&&(!prev||g.has(prev.id));return `<div class="talent ${learned?'learned':''}"><div class="tier">TIER ${t.tier} · LEVEL ${t.tier}</div><h4>${t.name}</h4><p>${t.desc}</p><button data-talent="${t.id}" ${can?'':'disabled'}>${learned?'✓ Learned':'Learn · 1 point'}</button></div>`;}).join('')}</div>`).join('')}</div><div class="section-label">INSTALLED AUGMENTATIONS</div><p>${g.p.augments.map(id=>D.items[id].name).join(' · ')||'Unmodified. Human is still a valid build.'}</p>`,'CHARACTER / PROGRESSION');}
function crafting(){view='craft';open('Make it through the night',`<p class="modal-intro">Craft anywhere for two turns. A Scrapper or nearby workbench reduces material costs. Crafting consumes time: find shelter before opening your toolkit.</p><div class="item-grid">${D.recipes.map(r=>{const cost=g.recipeCost(r),can=Object.entries(cost).every(([id,n])=>g.count(id)>=n);return `<div class="item-card"><div class="item-type">${D.items[r.id].type} · OUTPUT ${r.n}</div><h4>${D.items[r.id].name}</h4><p>${describe(r.id)}</p><p>${Object.entries(cost).map(([id,n])=>`<span style="color:${g.count(id)>=n?'#9bc8af':'#dd9288'}">${D.items[id].name} ${g.count(id)}/${n}</span>`).join(' · ')}</p><button class="small" data-craft="${r.id}" ${can?'':'disabled'}>Craft ${r.n}</button></div>`;}).join('')}</div>`,'SURVIVAL / CRAFTING');}
function city(){view='city';open('The city is larger than you',`<p class="modal-intro">Routes connect distinct, persistent districts. Find ↗ exits on each map to travel. Atlas entries are rumors; interiors remain unknown until explored. ⇄ ducts offer shortcuts to agile survivors.</p><div class="map-grid">${D.zones.map((z,i)=>`<div class="zone-card ${g.s.zone===i?'current':''}"><div class="eyebrow" style="color:${z.color}">0${i+1} / ${g.s.zone===i?'YOU ARE HERE':g.s.visited.includes(i)?'EXPLORED':'RUMORED'}</div><h3>${z.name}</h3><p>${z.kind} · Threat ${z.danger}</p><p>${z.sub}</p><div class="connections">ROUTES → ${z.links.map(n=>D.zones[n].name).join(' / ')}</div><p>${g.s.flags['objective'+i]?'✓ Objective resolved':z.objective}</p></div>`).join('')}</div>`,'CITY ATLAS / EIGHT DISTRICTS');}
function journal(){view='journal';open('Things the city remembers',`<div class="tabs"><button data-act="journal">Threads & record</button><button data-act="factionguide">Factions & escape</button></div><div class="item-grid">${D.zones.map((z,i)=>`<div class="item-card"><div class="item-type">${g.s.flags['objective'+i]?'RESOLVED':g.s.quests['main'+i]?'ACTIVE':'UNDISCOVERED'} · ${z.name}</div><h4>${z.objective}</h4><p>${g.s.flags['objective'+i]?'Your decision changed local reputation.':g.s.quests['main'+i]?'Find '+z.object+' in the far rooms of this district.':'Speak to '+z.npc+' for the story.'}</p>${g.s.quests['local'+i]?`<p>Local contract: ${g.s.quests['local'+i].state}${g.localReady(i)?' · Ready to turn in':''}</p>`:''}</div>`).join('')}</div><div class="section-label">YOUR RUN / ${g.s.history.length} MEMORIES</div>${g.s.history.slice().reverse().map(h=>`<div class="journal-entry"><small>DAY ${h.day}</small><p>${esc(h.text)}</p></div>`).join('')}`,'JOURNAL / '+g.p.name.toUpperCase());}
function factionGuide(){view='factionguide';open('Alliances have a cost',`<div class="item-grid">${D.factions.map(f=>`<div class="item-card"><div class="item-type" style="color:${f.color}">REPUTATION ${g.s.rep[f.id]}</div><h4>${f.name}</h4><p>${f.goal}</p><p>${f.benefit}</p><p>Rival: ${D.factions.find(x=>x.id===f.enemy).name}. Below −20: services close. At +15: trust and clearance. At +45: a permanent place in the faction.</p></div>`).join('')}</div><div class="section-label">ESCAPE ROUTES</div><div class="guide-grid"><div><h3>01 / THE LAST TRAIN</h3><p>Resolve Rainline and Cinderworks. Bring 8 scrap to the train in Rainline. Requires Union reputation 15 or intellect 6.</p></div><div><h3>02 / CORPORATE EXTRACTION</h3><p>Resolve Glass Meridian. Bring 160 credits to its landing pad with Directorate reputation 15.</p></div><div><h3>03 / THE IMPOSSIBLE DOOR</h3><p>Resolve the Spire. Bring 3 fragments to the door at night. District objectives and signal events yield fragments.</p></div><div><h3>04 / A PLACE TO STAY</h3><p>Earn 45 reputation with a faction, then pledge yourself through one of its contacts. Staying is also an ending.</p></div></div>`,'FACTIONS / FUTURES');}
function renderPrompt(){const p=g.prompt;if(!p)return;if(p.kind==='shop'){shop();return;}if(p.kind==='augments'){augments();return;}if(p.kind==='craft'){crafting();return;}view='prompt';open(p.title,`<p class="modal-intro">${esc(p.text)}</p><div class="choice-list">${p.options.map(o=>`<button data-choice="${o.id}" ${o.disabled?'disabled':''}>${esc(o.label)} <span style="float:right;color:var(--mint)">→</span></button>`).join('')}</div><div class="footer-actions"><button data-act="close">Return to the street</button></div>`,'ENCOUNTER / '+D.zones[g.s.zone].name.toUpperCase());}
function shop(){view='shop';const stock=g.shopStock();open('The neighborhood exchange',`<div class="inventory-summary"><span>${g.p.credits} CREDITS</span><span>LOCAL REPUTATION ${g.s.rep[D.zones[g.s.zone].faction]}</span></div><p class="modal-intro">Finite stock. Buy cartridges in batches of 10; other supplies one at a time. Equipment can be sold below.</p><div class="item-grid">${Object.entries(stock).filter(([id,n])=>n>0).map(([id,n])=>{let q=id==='ammo'?Math.min(n,10):1,cost=g.price(id)*q;return `<div class="item-card"><div class="item-type">${D.items[id].type} · ${n} IN STOCK</div><h4>${D.items[id].name}</h4><p>${describe(id)}</p><button class="small" data-buy="${id}" data-qty="${q}" ${g.p.credits<cost?'disabled':''}>Buy ${q} · ${cost} ¢</button></div>`;}).join('')}</div><div class="section-label">SELL FROM YOUR PACK</div><div class="item-grid">${g.p.inventory.map(i=>`<div class="item-card"><h4>${D.items[i.id].name} × ${i.qty}${['weapon','armor','gear'].some(s=>g.p[s]===i.uid)?' · Equipped':''}</h4><button class="small" data-sell="${i.uid}">Sell one · ${g.price(i.id,true)} ¢</button></div>`).join('')}</div>`,'TRADE / '+D.zones[g.s.zone].npc.toUpperCase());}
function augments(){view='augments';const strain=g.p.augments.reduce((n,id)=>n+D.items[id].strain,0),available=g.p.inventory.filter(i=>['chrome','flesh'].includes(D.items[i.id].type));open('How much of you is enough?',`<div class="inventory-summary"><span>STRAIN ${strain} / 7 SAFE</span><span>${g.p.credits} CREDITS</span></div><p class="modal-intro">Above 7 strain, your modifications drain energy every 10 turns; when empty, rejection damages you. Chrome gains Choir trust and loses Garden trust. Flesh reverses this. Mixed systems raise Echo exposure. Buy augmentations from faction exchanges.</p><div class="section-label">READY FOR INSTALLATION</div><div class="item-grid">${available.map(i=>`<div class="item-card"><div class="item-type">${D.items[i.id].type} · ${D.items[i.id].strain} STRAIN</div><h4>${D.items[i.id].name}</h4><p>${D.items[i.id].desc}</p><button class="small" data-install="${i.id}" ${g.has(i.id)||g.p.credits<30?'disabled':''}>${g.has(i.id)?'Already installed':'Install · 30 credits'}</button></div>`).join('')||'<p class="empty">No augmentations in your pack.</p>'}</div><div class="section-label">PART OF YOU</div><div class="item-grid">${g.p.augments.map(id=>`<div class="item-card"><h4>${D.items[id].name}</h4><p>${D.items[id].desc}</p><button class="small" data-remove="${id}" ${g.p.credits<20?'disabled':''}>Remove · 20 credits</button></div>`).join('')||'<p class="empty">Your body is still your own.</p>'}</div>`,'CLINIC / CHROME & FLESH');}
function pause(){view='pause';open('A moment between footsteps',`<p class="modal-intro">The city waits for your next action. Your run saves automatically after each change.</p><div class="choice-list"><button class="primary" data-act="close">Return to the night</button><button data-act="inventory">Inventory & supplies</button><button data-act="talents">Character & talents</button><button data-act="city">City atlas</button><button data-act="journal">Journal</button><button data-act="export">Export save file</button><button data-act="import">Import save file</button><button data-act="settings">Settings</button><button data-act="install">Install app / offline status</button><button data-act="menu">Save & return to title</button></div>`,'PAUSE');}
function settingScreen(){view='settings';open('Tune the signal',`<div class="setting-row"><div><b>Sound effects</b><p>Quiet procedural combat and interface audio.</p></div><button data-setting="sound">${settings.sound?'On':'Off'}</button></div><div class="setting-row"><div><b>Combat animation</b><p>Floating damage and weapon traces.</p></div><button data-setting="motion">${settings.motion?'On':'Off'}</button></div><div class="setting-row"><div><b>High contrast text</b><p>Brighter labels and panel borders.</p></div><button data-setting="contrast">${settings.contrast?'On':'Off'}</button></div><div class="footer-actions"><button data-act="close">Done</button></div>`,'SETTINGS / ACCESSIBILITY');}
function help(){view='help';open('A field guide to staying alive',`<div class="guide-grid"><div><h3>01 / YOUR FIRST MINUTES</h3><p>Speak to Mara, one step east of your starting tile. Take her work, buy supplies, and spend your starting talent point. Loot nearby lockers. Return to the cot when hurt. The objective is deeper southeast.</p></div><div><h3>02 / MOVE DELIBERATELY</h3><p>WASD or arrows move. Bump a hostile to attack with your weapon. Click a visible enemy to fire; Tab selects a target and F fires. E interacts within one tile. Click known floor to walk; movement stops on danger. Shift + a direction dashes for 5 energy.</p></div><div><h3>03 / TIME & DARKNESS</h3><p>Every turn costs five minutes. Night is 19:00–06:00: shorter sight, better stealth, rare cache salvage, wandering threats, and an open Echo door. Beds advance time safely but consume food and water.</p></div><div><h3>04 / FIGHT OR VANISH</h3><p>1 activates your class power. X toggles stealth. Walls and closed doors block sight and fire; furniture grants ranged cover. Enemies hear guns, pursue, flank, flee or keep their distance. Smoke breaks pursuit. Fighting is not required to claim objectives.</p></div><div><h3>05 / CARRY YOUR FUTURE</h3><p>I opens your pack. H uses a trauma kit, or a bandage if no kit remains. Food and water prevent deprivation. Injuries tick until treated. K crafts. Drop equipment on the ground or salvage it. Weapons lose condition; repair them at a bench or with a kit.</p></div><div><h3>06 / KNOW THE MARKS</h3><p>♙ contact · ▣ cache · ⌂ bed · ⚒ bench · ◈ objective · ? event · ↗ district route · ⇄ shortcut · ◎ ending. Unexplored tiles are hidden; remembered rooms are dim. Only currently visible inhabitants are shown.</p></div><div><h3>07 / BUILD A LIFE</h3><p>C opens talents: one of two exclusive paths per class. Learn its three talents, or invest in attributes. Clinics install Chrome and Flesh bought from faction vendors. Heavy augmentation drains energy; mostly human builds avoid that cost.</p></div><div><h3>08 / LEAVE A STORY</h3><p>J tracks quests. M shows district connections. Faction allies open services and endings; rivals close them. There are three escape routes plus faction futures. Death deletes the active local save. Exported saves remain yours. No power bonuses carry between runs—only knowledge.</p></div></div><div class="notice">Keyboard: E interact · 1 ability · X sneak · H heal · I inventory · C character · J journal · M atlas · K craft · Tab target · F fire · Space / . wait · Escape pause. Menus pause the city until you take an action.</div>`,'FIELD GUIDE / READ BEFORE THE RAIN');}
function ending(){view='ending';const e=g.s.ending;open(({death:'The light stays on',train:'The last train out',air:'Above the fracture',echo:'A city that never broke',faction:'A name in the neighborhood'})[e.type],`<div class="eyebrow">${e.type==='death'?'END OF A LIFE':'END OF A RUN'} / ${esc(g.p.name)} / ${g.p.specialization||D.classes.find(c=>c.id===g.p.cls).name}</div><p class="ending-text">${esc(e.text)}</p><div class="ending-grid"><div><b>${g.day}</b><span>DAYS TOUCHED</span></div><div><b>${g.p.level}</b><span>FINAL LEVEL</span></div><div><b>${g.s.visited.length}/8</b><span>DISTRICTS</span></div><div><b>${g.s.kills}</b><span>ENEMIES DEFEATED</span></div></div><div class="section-label">THE THINGS THAT MATTERED</div>${g.s.history.slice(-6,-1).map(h=>`<div class="journal-entry"><small>DAY ${h.day}</small><p>${esc(h.text)}</p></div>`).join('')}<div class="footer-actions"><button data-act="exportstory">Keep this story</button><button class="primary" data-act="newlife">Another life →</button><button data-act="menu">Title screen</button></div>`,'FRACTURED CITY / NIGHT RUN');}
async function download(name,text,type='application/json'){if(navigator.share&&navigator.canShare&&matchMedia('(pointer: coarse)').matches){const file=new File([text],name,{type});if(navigator.canShare({files:[file]})){try{await navigator.share({files:[file],title:name});return;}catch(err){if(err.name==='AbortError')return;}}}let blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function act(a){sound();switch(a){case'create':case'newlife':creation();break;case'start':{createName=$('runnerName').value.trim()||'Ash';createSeed=$('citySeed').value.trim();let game=new NRGame();game.newRun(createName,selectedClass,createSeed);attach(game);break;}case'continue':try{attach(NRGame.load(localStorage.getItem(SAVE)));}catch(err){open('Save could not be loaded',`<p>${esc(err.message)}</p><p>Import an exported save, or start a new life.</p>`);}break;case'close':close();break;case'inventory':if(g)inventory();break;case'talents':if(g)talents();break;case'city':if(g)city();break;case'journal':if(g)journal();break;case'factionguide':factionGuide();break;case'craft':if(g)crafting();break;case'help':help();break;case'settings':settingScreen();break;case'install':installation();break;case'installnative':window.NightRunPWA?.install();break;case'applyupdate':window.NightRunPWA?.applyUpdate();break;case'target':cycleTarget();break;case'fire':fireTarget();break;case'dashmode':dashMode=!dashMode;$('dashButton').setAttribute('aria-pressed',String(dashMode));$('dashButton').textContent='Dash: '+(dashMode?'on':'off');break;case'pause':if(g)pause();break;case'interact':g?.interact();break;case'ability':g?.ability();break;case'sneak':g?.toggleSneak();break;case'wait':g?.tick();break;case'heal':{let i=g?.p.inventory.find(i=>i.id==='medkit')||g?.p.inventory.find(i=>i.id==='bandage');if(i)g.use(i.uid);else if(g){g.log('No medical supplies. Craft a dressing or find a clinic.','bad');g.changed();}break;}case'export':if(g)download('Night-Run-'+g.p.name.replace(/[^a-z0-9]/gi,'-')+'.json',g.serialize());break;case'exportstory':download('Night-Run-story.txt',`${g.p.name} — ${g.s.ending.type}\nCity seed: ${g.s.seed}\n\n`+g.s.history.map(h=>`DAY ${h.day}: ${h.text}`).join('\n\n'),'text/plain');break;case'import':$('saveFile').click();break;case'menu':stopWalk();document.body.classList.remove('playing');$('modal').hidden=true;$('gameScreen').hidden=true;$('titleScreen').hidden=false;view='';try{$('continueButton').disabled=!localStorage.getItem(SAVE);}catch{}skyline();break;case'zoomin':tileSize=Math.min(44,tileSize+4);draw();break;case'zoomout':tileSize=Math.max(20,tileSize-4);draw();break;}}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-act]');if(!b||b.disabled)return;const d=b.dataset;if(d.act){act(d.act);return;}sound();if(d.class){createName=$('runnerName')?.value||createName;createSeed=$('citySeed')?.value||'';selectedClass=d.class;creation();}if(d.move&&g){stopWalk();const movement=d.move.split(',').map(Number);if(dashMode)g.dash(...movement);else g.move(...movement);}if(d.choice){$('modal').hidden=true;view='';g.choose(d.choice);}if(d.filter){filter=d.filter;inventory();}if(d.use){const i=g.p.inventory.find(i=>i.uid===+d.use);if(i?.id==='grenade'&&!target){close();g.log('Select a visible target with Tab, then use the grenade from your inventory.','hint');g.changed();}else g.use(+d.use,g.map.entities.find(e=>e.uid===target));}if(d.drop)g.drop(+d.drop);if(d.salvage)g.drop(+d.salvage,true);if(d.talent)g.learn(d.talent);if(d.stat)g.train(+d.stat);if(d.craft)g.craft(d.craft);if(d.buy)g.buy(d.buy,+d.qty);if(d.sell)g.sell(+d.sell);if(d.install)g.install(d.install);if(d.remove)g.removeAugment(d.remove);if(d.entity){let en=g.map.entities.find(e=>e.uid===+d.entity);if(en.type==='enemy'){target=en.uid;draw();}else if(NRDist(g.p,en)<=1)g.interact(en);else{g.log(en.name+' is '+NRDist(g.p,en)+' tiles away. Move closer.','hint');g.changed();}}if(d.setting){settings[d.setting]=!settings[d.setting];applySettings();settingScreen();}});
$('saveFile').addEventListener('change',async e=>{let f=e.target.files[0];if(!f)return;try{if(f.size>5e6)throw Error('Save exceeds the 5 MB limit.');let game=NRGame.load(await f.text());attach(game);}catch(err){open('Cannot read this save',`<p>${esc(err.message)}</p>`);}e.target.value='';});
document.addEventListener('keydown',e=>{if(e.target.matches('input'))return;if(!$('modal').hidden){if(e.key==='Escape'){e.preventDefault();close();}return;}if(!g||!$('titleScreen').hidden||g.s.ending)return;const key=e.key.toLowerCase(),moves={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0],q:[-1,-1],z:[-1,1]};if(moves[key]){e.preventDefault();stopWalk();if(e.shiftKey)g.dash(...moves[key]);else g.move(...moves[key]);return;}const actions={e:'interact','1':'ability',x:'sneak',i:'inventory',c:'talents',j:'journal',m:'city',k:'craft',h:'heal',escape:'pause','?':'help','.':'wait',' ':'wait'};if(actions[key]){e.preventDefault();stopWalk();act(actions[key]);}if(key==='tab'){e.preventDefault();let enemies=g.living().filter(en=>!en.ally&&g.seen(en));if(enemies.length){let i=enemies.findIndex(en=>en.uid===target);target=enemies[(i+1)%enemies.length].uid;draw();}}if(key==='f'){e.preventDefault();let en=g.map.entities.find(en=>en.uid===target)||g.living().find(en=>g.seen(en)&&!en.ally);if(en)g.attack(en);}});
function tileAt(e){const c=$('mapCanvas'),r=c.getBoundingClientRect(),scale=Math.min(r.width/c.width,r.height/c.height),left=(r.width-c.width*scale)/2,top=(r.height-c.height*scale)/2;return{x:Math.floor((e.clientX-r.left-left)/scale/tileSize+cam.x),y:Math.floor((e.clientY-r.top-top)/scale/tileSize+cam.y)};}
$('mapCanvas').addEventListener('click',e=>{if(!g||g.s.ending)return;stopWalk();let p=tileAt(e);if(p.x<0||p.y<0||p.x>=g.map.w||p.y>=g.map.h)return;let en=g.map.entities.find(en=>en.x===p.x&&en.y===p.y&&en.type==='enemy'&&en.hp>0&&!en.ally&&g.seen(en));if(en){target=en.uid;g.attack(en);return;}let obj=g.map.entities.find(en=>en.x===p.x&&en.y===p.y&&en.type!=='enemy'&&!(en.type==='cache'&&en.opened));if(obj&&NRDist(obj,g.p)<=1){g.interact(obj);return;}walkTo(p);});
$('mapCanvas').addEventListener('mousemove',e=>{if(!g)return;const p=tileAt(e),en=g.map.entities.find(en=>en.x===p.x&&en.y===p.y&&g.seen(en)&&!(en.type==='enemy'&&en.hp<=0));if(en){$('hoverTip').hidden=false;$('hoverTip').textContent=en.name+(en.type==='enemy'?` · ${en.hp}/${en.maxHp} HP · ${en.damage} damage · range ${en.range}`:' · '+(NRDist(en,g.p)<=1?'Click to interact':'Move within 1 tile'));}else $('hoverTip').hidden=true;});$('mapCanvas').addEventListener('mouseleave',()=>$('hoverTip').hidden=true);
function stopWalk(){if(autoWalk)clearInterval(autoWalk);autoWalk=null;}
function walkTo(dest){if(!g.map.seen[dest.y*g.map.w+dest.x])return;let q=[{x:g.p.x,y:g.p.y,path:[]}],visited=new Set([g.p.y*g.map.w+g.p.x]),path=null;while(q.length){let n=q.shift();if(n.x===dest.x&&n.y===dest.y){path=n.path;break;}for(let [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){let x=n.x+dx,y=n.y+dy,k=y*g.map.w+x;if(x<0||y<0||x>=g.map.w||y>=g.map.h||visited.has(k)||!g.map.seen[k]||g.tile(x,y)==='#'||g.enemyAt(x,y)||g.map.entities.some(e=>e.type==='npc'&&e.x===x&&e.y===y))continue;visited.add(k);q.push({x,y,path:[...n.path,[dx,dy]]});}}if(!path?.length)return;let step=()=>{if(!path.length||g.s.ending||!$('modal').hidden){stopWalk();return;}let [dx,dy]=path[0],door=g.tile(g.p.x+dx,g.p.y+dy)==='+';g.move(dx,dy);if(!door)path.shift();if(g.living().some(en=>!en.ally&&g.seen(en)))stopWalk();};autoWalk=setInterval(step,130);step();}
function skyline(){const c=$('skyline'),ctx=c.getContext('2d'),w=c.width=window.innerWidth,h=c.height=window.innerHeight;let rand=(x)=>{const v=Math.sin(x*127.1+311.7)*43758.5453;return v-Math.floor(v);};const grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#0e1e2b');grad.addColorStop(.6,'#30464b');grad.addColorStop(1,'#0d1a24');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.fillStyle='#b9cfbf';ctx.beginPath();ctx.arc(w*.73,h*.25,38,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6da89715';for(let i=3;i>0;i--){ctx.beginPath();ctx.arc(w*.73,h*.25,38+i*10,0,Math.PI*2);ctx.fill();}
 for(let layer=0;layer<3;layer++){let bw=60+layer*40,base=h*(.77+layer*.12);for(let i=0;i<w/bw+2;i++){let x=i*bw-20+(layer%2)*35,bh=(120+rand(i+layer*31)*240)*(1+layer*.18),y=base-bh;ctx.fillStyle=['#21343e','#182b34','#101f29'][layer];ctx.fillRect(x,y,bw-5,bh);ctx.fillStyle='#62747844';ctx.fillRect(x,y,bw-5,3);if(rand(i*4+layer)>.55){ctx.fillStyle='#29404a';ctx.fillRect(x+10,y-18,bw*.4,18);ctx.fillStyle='#57737b';ctx.fillRect(x+bw/2,y-65,2,65);ctx.fillStyle='#cb7565';ctx.fillRect(x+bw/2-1,y-66,4,4);}for(let yy=y+15;yy<base;yy+=20)for(let xx=x+10;xx<x+bw-15;xx+=13){let r=rand(xx+yy+layer);if(r>.58){ctx.fillStyle=r>.9?'#c2b37a88':r>.76?'#84b2a75c':'#47647166';ctx.fillRect(xx,yy,5,8);}}if(layer===2&&i===Math.floor(w/bw*.75)){ctx.fillStyle='#203b3c';ctx.fillRect(x+12,y+50,36,132);ctx.fillStyle='#98c2a0';ctx.font='18px monospace';['N','I','G','H','T'].forEach((n,j)=>ctx.fillText(n,x+24,y+72+j*23));}}}
 ctx.strokeStyle='#9ac1c515';for(let i=0;i<130;i++){let x=rand(i+100)*w,y=rand(i+240)*h;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-12,y+40);ctx.stroke();}ctx.strokeStyle='#051018';ctx.lineWidth=3;for(let j=0;j<3;j++){ctx.beginPath();ctx.moveTo(w*.35,0);ctx.quadraticCurveTo(w*.65,h*.5+j*18,w,h*.34+j*22);ctx.stroke();}}
window.addEventListener('resize',()=>{if(!$('titleScreen').hidden)skyline();else draw();});skyline();

function cycleTarget(){
 if(!g||g.s.ending)return;
 const enemies=g.living().filter(e=>!e.ally&&g.seen(e)).sort((a,b)=>NRDist(g.p,a)-NRDist(g.p,b));
 if(!enemies.length){target=null;g.log('No hostile in sight.','hint');g.changed();return;}
 const index=enemies.findIndex(e=>e.uid===target);
 const enemy=enemies[(index+1)%enemies.length];target=enemy.uid;
 g.log('Target: '+enemy.name+' · '+enemy.hp+' HP · '+NRDist(g.p,enemy)+' tiles.','hint');g.changed();
}
function fireTarget(){
 if(!g||g.s.ending)return;
 const enemy=g.living().find(e=>e.uid===target&&!e.ally&&g.seen(e))||g.living().filter(e=>!e.ally&&g.seen(e)).sort((a,b)=>NRDist(g.p,a)-NRDist(g.p,b))[0];
 if(enemy){target=enemy.uid;g.attack(enemy);}else{g.log('No hostile in sight.','hint');g.changed();}
}
function installation(){
 view='install';const platform=window.NightRunPWA?.getState()||{};
 open('Take the city with you',`<img class="install-icon" src="${esc(document.querySelector('.brand-icon')?.src||'icons/icon-192.png')}" alt="Night Run fractured skyline logo"><p class="modal-intro">${platform.installed?'You are playing the installed app.':"Install Night Run on your home screen for an app-sized view and offline play."}</p><ol class="install-steps"><li>Open the live game in <strong>Safari on your iPhone</strong>.</li><li>Tap <strong>Share</strong>, then <strong>Add to Home Screen</strong>.</li><li>Keep <strong>Open as Web App</strong> enabled if shown, then tap <strong>Add</strong>.</li><li>Open the new <strong>Night Run</strong> icon once while online. Wait for <strong>Ready to play offline</strong>.</li></ol><div class="notice">${platform.offline?'✓ The game is cached on this browser and ready for offline play.':platform.hosted?platform.error||'The offline copy is being prepared. Keep this page open for a moment.':'This portable HTML file can play offline, but installation needs the hosted HTTPS game.'}</div><p class="modal-intro" style="margin-top:18px">Your run is saved on this device. Safari and the home-screen app can have separate storage. Use <strong>Export save</strong> → <strong>Save to Files</strong>, then <strong>Import save</strong> inside the installed app to transfer a run. Keep an exported backup before clearing browser data.</p><div class="footer-actions">${platform.canPrompt?'<button class="primary" data-act="installnative">Install Night Run</button>':''}${platform.update?'<button class="primary" data-act="applyupdate">Save & apply update</button>':''}<button data-act="close">Done</button></div>`,'INSTALL / OFFLINE PLAY');
}
function persistCurrentRun(){
 stopWalk();if(!g||g.s.ending)return;
 try{localStorage.setItem(SAVE,g.serialize());}catch{if($('saveState'))$('saveState').textContent='EXPORT SAVE TO KEEP PROGRESS';}
}
window.addEventListener('pagehide',persistCurrentRun);
window.addEventListener('night-run-save-request',persistCurrentRun);
document.addEventListener('visibilitychange',()=>{if(document.hidden){persistCurrentRun();audioCtx?.suspend();}});
window.addEventListener('night-run-platform',()=>{if(view==='install'&&!$('modal').hidden)installation();});
if('ResizeObserver' in window)new ResizeObserver(()=>{if(g&&!$('gameScreen').hidden)draw();}).observe(document.querySelector('.canvas-wrap'));
})();
